import { useNavigate } from "react-router-dom";
import { CircleDollarSign, Landmark, PackageX, Factory, PlusCircle, BookOpenCheck } from "lucide-react";
import useFetch from "../../../hooks/useFetch";
import { getDashboard, getJournal, getStockAlerts } from "../services/dashboard.api";
import Loader from "../../../components/common/Loader";
import Button from "../../../components/common/Button";
import StatCard from "../components/StatCard";
import RecentSales from "../components/RecentSales";
import StockAlerts from "../components/StockAlerts";
import SalesChart from "../../../components/charts/SalesChart";
import { formatCurrency } from "../../../utils/currency";

export default function DashboardPage() {
  const navigate=useNavigate(); const state=useFetch(async()=>{const [dashboard,journal,alerts]=await Promise.all([getDashboard(),getJournal(),getStockAlerts()]);return{dashboard,journal,alerts};},[]);
  if(state.loading)return <Loader/>; const d=state.data?.dashboard||{};
  return <div className="page"><header className="page-header"><div><span className="eyebrow">Vue strategique consolidee // db_pvc_renovee live</span><h1>Cockpit General & Tresorerie</h1><p>Indicateurs industriels, commerciaux et financiers synchronises en temps reel.</p></div><div className="page-actions"><Button variant="primary" icon={PlusCircle} onClick={()=>navigate("/ventes")}>Nouvelle vente PF</Button><Button icon={BookOpenCheck} onClick={()=>navigate("/comptabilite/ecritures")}>Ecriture journal</Button></div></header><section className="metrics"><StatCard label="Ventes produits finis" value={formatCurrency(d.ventes_mois?.chiffre_affaires)} detail={`${d.ventes_mois?.nombre||0} ventes ce mois`} icon={CircleDollarSign} progress={72}/><StatCard label="Resultat net exploitation" value={formatCurrency(0)} detail="Synthese SYSCOHADA" icon={Landmark} tone="green" progress={64}/><StatCard label="Creances clients" value={formatCurrency(d.creances_clients)} detail="Solde encore a recouvrer" icon={CircleDollarSign} tone="orange" progress={42}/><StatCard label="Stock critique matiere" value={`${d.alertes_stock||0} alerte(s)`} detail="Sous le seuil minimum" icon={PackageX} tone={d.alertes_stock?"red":"green"} progress={d.alertes_stock?24:100}/></section><section className="dashboard-grid"><div className="panel"><div className="panel-head"><div><h2>Equilibre Industriel : Ventes vs Couts d'Extrusion</h2><p>Projection hebdomadaire consolidee</p></div><span className="badge">USD</span></div><div className="chart-wrap"><SalesChart total={Number(d.ventes_mois?.chiffre_affaires||0) / 4}/></div></div><div className="panel"><div className="panel-head"><div><h2>Capacite Usine & Extrusion</h2><p>Rendement synthetique</p></div><span className="badge green">ONLINE</span></div><div className="panel-body" style={{textAlign:"center",padding:"28px"}}><Factory size={42} color="var(--green)"/><div className="metric-value" style={{marginTop:10}}>{d.produits_finis?.nombre||0}</div><div className="micro" style={{color:"var(--muted)",fontSize:9}}>References produits finis</div></div></div></section><section className="dashboard-grid"><div className="panel"><div className="panel-head"><div><h2>Operations Recentes</h2><p>Flux des ventes produits finis</p></div><span className="badge">v_ventes_clients</span></div><RecentSales rows={d.ventes_recentes}/></div><div className="side-stack"><div className="panel"><div className="panel-head"><div><h2>Stocks Matieres en Alerte</h2><p>Seuil de securite usine</p></div><span className="badge red">Urgent</span></div><StockAlerts rows={state.data?.alerts}/></div><div className="panel"><div className="panel-head"><h2>Effectifs Usine</h2><span className="badge green">Actifs</span></div><div className="panel-body"><div className="metric-value green">{d.personnel_actif||0}</div><small>collaborateurs actifs aujourd'hui</small></div></div></div></section></div>;
}
