import { useEffect, useState } from "react";
import { PlusCircle } from "lucide-react";
import useFetch from "../../../hooks/useFetch";
import { createEntry, getExchangeRate, listEntries, listJournals, listSubAccounts } from "../services/comptabilite.api";
import AccountingNav from "../components/AccountingNav";
import Button from "../../../components/common/Button";
import Modal from "../../../components/common/Modal";
import Input from "../../../components/common/Input";
import Select from "../../../components/common/Select";
import Table from "../../../components/common/Table";
import Badge from "../../../components/common/Badge";
import Loader from "../../../components/common/Loader";
import { formatCurrency } from "../../../utils/currency";
import { formatDate } from "../../../utils/dates";

export default function EcrituresPage() {
  const state = useFetch(async () => { const [entries, journals, subAccounts, rate] = await Promise.all([listEntries(), listJournals(), listSubAccounts(), getExchangeRate()]); return { entries, journals, subAccounts, rate }; }, []);
  const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [form, setForm] = useState({ sens: "C", um: "USD", date_ecriture: new Date().toISOString().slice(0, 16) });
  useEffect(() => { if (state.data?.rate?.taux) setForm((current) => ({ ...current, taux_convertion_usd_fc: state.data.rate.taux })); }, [state.data?.rate?.taux]);
  if (state.loading) return <Loader />;
  const { entries = [], journals = [], subAccounts = [], rate = {} } = state.data || {};
  const openForm = () => { setError(""); setForm({ sens: "C", um: "USD", taux_convertion_usd_fc: rate.taux || 2850, date_ecriture: new Date().toISOString().slice(0, 16) }); setOpen(true); };
  const submit = async () => { try { await createEntry({ ...form, journal_id: Number(form.journal_id), sous_compte_id: Number(form.sous_compte_id), sous_compte_cp: form.sous_compte_cp ? Number(form.sous_compte_cp) : null, montant: Number(form.montant), taux_convertion_usd_fc: Number(form.taux_convertion_usd_fc) }); setOpen(false); await state.refresh(); } catch (err) { setError(err.message); } };
  const columns = [{key:"date_ecriture",label:"Date",render:formatDate},{key:"numdocument",label:"Piece",render:(value)=><span className="mono">{value}</span>},{key:"journal_id",label:"Journal",render:(value)=>journals.find((row)=>row.id===value)?.codejr||value},{key:"sous_compte_id",label:"Sous-compte",render:(value)=>subAccounts.find((row)=>row.id===value)?.intitule||value},{key:"sens",label:"Sens",render:(value)=><Badge tone={value==="C"?"green":"orange"}>{value}</Badge>},{key:"libelle",label:"Libelle"},{key:"montant",label:"Montant",numeric:true,render:(value)=>formatCurrency(value)}];
  return <div className="page"><header className="page-header"><div><span className="eyebrow">Saisie comptable // pieces justificatives</span><h1>Saisie des Ecritures</h1><p>Creation et consultation des ecritures avant lecture dans le journal.</p></div><Button variant="primary" icon={PlusCircle} onClick={openForm}>Passer une ecriture</Button></header><AccountingNav/><section className="panel"><div className="panel-head"><div><h2>Registre des ecritures saisies</h2><p>{entries.length} pieces enregistrees</p></div><Badge>tecritures_comptables</Badge></div><Table rows={entries} columns={columns}/></section><Modal open={open} title="Nouvelle ecriture comptable" onClose={()=>setOpen(false)} footer={<><Button onClick={()=>setOpen(false)}>Annuler</Button><Button variant="primary" onClick={submit}>Valider l'ecriture</Button></>}>{error&&<div className="form-error">{error}</div>}<div className="form-grid"><Select label="Journal" value={form.journal_id||""} onChange={(event)=>setForm({...form,journal_id:event.target.value})} options={[{value:"",label:"Selectionner"},...journals.map((row)=>({value:row.id,label:`${row.codejr} - ${row.nom_journal}`}))]}/><Input label="Numero document" value={form.numdocument||""} onChange={(event)=>setForm({...form,numdocument:event.target.value})}/><Select label="Sous-compte" value={form.sous_compte_id||""} onChange={(event)=>setForm({...form,sous_compte_id:event.target.value})} options={[{value:"",label:"Selectionner"},...subAccounts.map((row)=>({value:row.id,label:`${row.numero} - ${row.intitule}`}))]}/><Select label="Contrepartie" value={form.sous_compte_cp||""} onChange={(event)=>setForm({...form,sous_compte_cp:event.target.value})} options={[{value:"",label:"Aucune"},...subAccounts.map((row)=>({value:row.id,label:`${row.numero} - ${row.intitule}`}))]}/><Select label="Sens" value={form.sens} onChange={(event)=>setForm({...form,sens:event.target.value})} options={[{value:"C",label:"C - Compte"},{value:"CP",label:"CP - Contrepartie"}]}/><Input label="Montant" type="number" min="0" step="0.01" value={form.montant||""} onChange={(event)=>setForm({...form,montant:event.target.value})}/><Select label="Devise" value={form.um} onChange={(event)=>setForm({...form,um:event.target.value})} options={["USD","FC"]}/><Input label="Taux USD/FC" type="number" value={form.taux_convertion_usd_fc||""} onChange={(event)=>setForm({...form,taux_convertion_usd_fc:event.target.value})}/><Input label="Date ecriture" type="datetime-local" value={form.date_ecriture} onChange={(event)=>setForm({...form,date_ecriture:event.target.value})}/><Input className="full" label="Libelle" value={form.libelle||""} onChange={(event)=>setForm({...form,libelle:event.target.value})}/></div></Modal></div>;
}
