--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 31/08/2026 16:44:54
-- Server version: 11.7.2
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE db_pvc_renovee;

--
-- Drop procedure `usp_tfamilles_comptables_Delete`
--
DROP PROCEDURE IF EXISTS usp_tfamilles_comptables_Delete;

--
-- Drop procedure `usp_tfamilles_comptables_Insert`
--
DROP PROCEDURE IF EXISTS usp_tfamilles_comptables_Insert;

--
-- Drop procedure `usp_tfamilles_comptables_Select`
--
DROP PROCEDURE IF EXISTS usp_tfamilles_comptables_Select;

--
-- Drop procedure `usp_tfamilles_comptables_Update`
--
DROP PROCEDURE IF EXISTS usp_tfamilles_comptables_Update;

--
-- Drop procedure `usp_tprofils_Delete`
--
DROP PROCEDURE IF EXISTS usp_tprofils_Delete;

--
-- Drop procedure `usp_tprofils_Insert`
--
DROP PROCEDURE IF EXISTS usp_tprofils_Insert;

--
-- Drop procedure `usp_tprofils_Select`
--
DROP PROCEDURE IF EXISTS usp_tprofils_Select;

--
-- Drop procedure `usp_tprofils_Update`
--
DROP PROCEDURE IF EXISTS usp_tprofils_Update;

--
-- Drop table `tjours_feries`
--
DROP TABLE IF EXISTS tjours_feries;

--
-- Drop table `t_familles_comptables`
--
DROP TABLE IF EXISTS t_familles_comptables;

--
-- Drop table `t_profils`
--
DROP TABLE IF EXISTS t_profils;

--
-- Drop procedure `pr_create_user`
--
DROP PROCEDURE IF EXISTS pr_create_user;

--
-- Drop procedure `pr_login_user`
--
DROP PROCEDURE IF EXISTS pr_login_user;

--
-- Drop table `tutilisateurs`
--
DROP TABLE IF EXISTS tutilisateurs;

--
-- Drop table `troles`
--
DROP TABLE IF EXISTS troles;

--
-- Drop view `v_balance_comptes`
--
DROP VIEW IF EXISTS v_balance_comptes CASCADE;

--
-- Drop view `v_balance_generale`
--
DROP VIEW IF EXISTS v_balance_generale CASCADE;

--
-- Drop view `v_bilan`
--
DROP VIEW IF EXISTS v_bilan CASCADE;

--
-- Drop view `v_compte_resultat`
--
DROP VIEW IF EXISTS v_compte_resultat CASCADE;

--
-- Drop view `v_journal_operations`
--
DROP VIEW IF EXISTS v_journal_operations CASCADE;

--
-- Drop view `v_resultat_net`
--
DROP VIEW IF EXISTS v_resultat_net CASCADE;

--
-- Drop view `v_synthese_financiere`
--
DROP VIEW IF EXISTS v_synthese_financiere CASCADE;

--
-- Drop procedure `usp_tecritures_comptables_Delete`
--
DROP PROCEDURE IF EXISTS usp_tecritures_comptables_Delete;

--
-- Drop procedure `usp_tecritures_comptables_Insert`
--
DROP PROCEDURE IF EXISTS usp_tecritures_comptables_Insert;

--
-- Drop procedure `usp_tecritures_comptables_Select`
--
DROP PROCEDURE IF EXISTS usp_tecritures_comptables_Select;

--
-- Drop procedure `usp_tecritures_comptables_Update`
--
DROP PROCEDURE IF EXISTS usp_tecritures_comptables_Update;

--
-- Drop table `tecritures_comptables`
--
DROP TABLE IF EXISTS tecritures_comptables;

--
-- Drop procedure `usp_tjournal_Delete`
--
DROP PROCEDURE IF EXISTS usp_tjournal_Delete;

--
-- Drop procedure `usp_tjournal_Insert`
--
DROP PROCEDURE IF EXISTS usp_tjournal_Insert;

--
-- Drop procedure `usp_tjournal_Select`
--
DROP PROCEDURE IF EXISTS usp_tjournal_Select;

--
-- Drop procedure `usp_tjournal_Update`
--
DROP PROCEDURE IF EXISTS usp_tjournal_Update;

--
-- Drop table `tjournal`
--
DROP TABLE IF EXISTS tjournal;

--
-- Drop procedure `usp_tdetails_commandeclient_Delete`
--
DROP PROCEDURE IF EXISTS usp_tdetails_commandeclient_Delete;

--
-- Drop procedure `usp_tdetails_commandeclient_Insert`
--
DROP PROCEDURE IF EXISTS usp_tdetails_commandeclient_Insert;

--
-- Drop procedure `usp_tdetails_commandeclient_Select`
--
DROP PROCEDURE IF EXISTS usp_tdetails_commandeclient_Select;

--
-- Drop procedure `usp_tdetails_commandeclient_Update`
--
DROP PROCEDURE IF EXISTS usp_tdetails_commandeclient_Update;

--
-- Drop table `tdetails_commandeclient`
--
DROP TABLE IF EXISTS tdetails_commandeclient;

--
-- Drop procedure `usp_tdetails_vente_Delete`
--
DROP PROCEDURE IF EXISTS usp_tdetails_vente_Delete;

--
-- Drop procedure `usp_tdetails_vente_Insert`
--
DROP PROCEDURE IF EXISTS usp_tdetails_vente_Insert;

--
-- Drop procedure `usp_tdetails_vente_Select`
--
DROP PROCEDURE IF EXISTS usp_tdetails_vente_Select;

--
-- Drop procedure `usp_tdetails_vente_Update`
--
DROP PROCEDURE IF EXISTS usp_tdetails_vente_Update;

--
-- Drop table `tdetails_vente`
--
DROP TABLE IF EXISTS tdetails_vente;

--
-- Drop procedure `usp_tentrees_pf_Delete`
--
DROP PROCEDURE IF EXISTS usp_tentrees_pf_Delete;

--
-- Drop procedure `usp_tentrees_pf_Insert`
--
DROP PROCEDURE IF EXISTS usp_tentrees_pf_Insert;

--
-- Drop procedure `usp_tentrees_pf_Select`
--
DROP PROCEDURE IF EXISTS usp_tentrees_pf_Select;

--
-- Drop procedure `usp_tentrees_pf_Update`
--
DROP PROCEDURE IF EXISTS usp_tentrees_pf_Update;

--
-- Drop table `tentrees_pf`
--
DROP TABLE IF EXISTS tentrees_pf;

--
-- Drop procedure `usp_tproduitfini_Delete`
--
DROP PROCEDURE IF EXISTS usp_tproduitfini_Delete;

--
-- Drop procedure `usp_tproduitfini_Insert`
--
DROP PROCEDURE IF EXISTS usp_tproduitfini_Insert;

--
-- Drop procedure `usp_tproduitfini_Select`
--
DROP PROCEDURE IF EXISTS usp_tproduitfini_Select;

--
-- Drop procedure `usp_tproduitfini_Update`
--
DROP PROCEDURE IF EXISTS usp_tproduitfini_Update;

--
-- Drop table `tproduitfini`
--
DROP TABLE IF EXISTS tproduitfini;

--
-- Drop table `taffect_avantages`
--
DROP TABLE IF EXISTS taffect_avantages;

--
-- Drop table `tavantages_salaire`
--
DROP TABLE IF EXISTS tavantages_salaire;

--
-- Drop table `tagent_retenues`
--
DROP TABLE IF EXISTS tagent_retenues;

--
-- Drop table `tretenues_salaire`
--
DROP TABLE IF EXISTS tretenues_salaire;

--
-- Drop table `tprendre_conges`
--
DROP TABLE IF EXISTS tprendre_conges;

--
-- Drop table `tconges`
--
DROP TABLE IF EXISTS tconges;

--
-- Drop view `v_balance_agee_consolide`
--
DROP VIEW IF EXISTS v_balance_agee_consolide CASCADE;

--
-- Drop view `v_balance_agee_fournisseurs`
--
DROP VIEW IF EXISTS v_balance_agee_fournisseurs CASCADE;

--
-- Drop view `v_stock_matiere`
--
DROP VIEW IF EXISTS v_stock_matiere CASCADE;

--
-- Drop procedure `usp_tentreematiere_Delete`
--
DROP PROCEDURE IF EXISTS usp_tentreematiere_Delete;

--
-- Drop procedure `usp_tentreematiere_Insert`
--
DROP PROCEDURE IF EXISTS usp_tentreematiere_Insert;

--
-- Drop procedure `usp_tentreematiere_Select`
--
DROP PROCEDURE IF EXISTS usp_tentreematiere_Select;

--
-- Drop procedure `usp_tentreematiere_Update`
--
DROP PROCEDURE IF EXISTS usp_tentreematiere_Update;

--
-- Drop table `tentreematiere`
--
DROP TABLE IF EXISTS tentreematiere;

--
-- Drop table `tagent_achat`
--
DROP TABLE IF EXISTS tagent_achat;

--
-- Drop view `v_paie_personnel`
--
DROP VIEW IF EXISTS v_paie_personnel CASCADE;

--
-- Drop table `taffectations_personnel`
--
DROP TABLE IF EXISTS taffectations_personnel;

--
-- Drop table `tpostes`
--
DROP TABLE IF EXISTS tpostes;

--
-- Drop view `v_plan_amortissement`
--
DROP VIEW IF EXISTS v_plan_amortissement CASCADE;

--
-- Drop procedure `pr_insert_plan_amort`
--
DROP PROCEDURE IF EXISTS pr_insert_plan_amort;

--
-- Drop table `tplan_amortissements`
--
DROP TABLE IF EXISTS tplan_amortissements;

--
-- Drop table `tmateriels`
--
DROP TABLE IF EXISTS tmateriels;

--
-- Drop procedure `usp_tcommandeclient_Delete`
--
DROP PROCEDURE IF EXISTS usp_tcommandeclient_Delete;

--
-- Drop procedure `usp_tcommandeclient_Insert`
--
DROP PROCEDURE IF EXISTS usp_tcommandeclient_Insert;

--
-- Drop procedure `usp_tcommandeclient_Select`
--
DROP PROCEDURE IF EXISTS usp_tcommandeclient_Select;

--
-- Drop procedure `usp_tcommandeclient_Update`
--
DROP PROCEDURE IF EXISTS usp_tcommandeclient_Update;

--
-- Drop table `tcommandeclient`
--
DROP TABLE IF EXISTS tcommandeclient;

--
-- Drop procedure `usp_tpaiements_clients_Delete`
--
DROP PROCEDURE IF EXISTS usp_tpaiements_clients_Delete;

--
-- Drop procedure `usp_tpaiements_clients_Insert`
--
DROP PROCEDURE IF EXISTS usp_tpaiements_clients_Insert;

--
-- Drop procedure `usp_tpaiements_clients_Select`
--
DROP PROCEDURE IF EXISTS usp_tpaiements_clients_Select;

--
-- Drop procedure `usp_tpaiements_clients_Update`
--
DROP PROCEDURE IF EXISTS usp_tpaiements_clients_Update;

--
-- Drop table `tpaiements_clients`
--
DROP TABLE IF EXISTS tpaiements_clients;

--
-- Drop view `v_balance_agee_clients`
--
DROP VIEW IF EXISTS v_balance_agee_clients CASCADE;

--
-- Drop view `v_ventes_clients`
--
DROP VIEW IF EXISTS v_ventes_clients CASCADE;

--
-- Drop procedure `usp_tventeproduitfini_Delete`
--
DROP PROCEDURE IF EXISTS usp_tventeproduitfini_Delete;

--
-- Drop procedure `usp_tventeproduitfini_Insert`
--
DROP PROCEDURE IF EXISTS usp_tventeproduitfini_Insert;

--
-- Drop procedure `usp_tventeproduitfini_Select`
--
DROP PROCEDURE IF EXISTS usp_tventeproduitfini_Select;

--
-- Drop procedure `usp_tventeproduitfini_Update`
--
DROP PROCEDURE IF EXISTS usp_tventeproduitfini_Update;

--
-- Drop table `tventeproduitfini`
--
DROP TABLE IF EXISTS tventeproduitfini;

--
-- Drop table `tclient`
--
DROP TABLE IF EXISTS tclient;

--
-- Drop procedure `usp_tsortiematiere_Delete`
--
DROP PROCEDURE IF EXISTS usp_tsortiematiere_Delete;

--
-- Drop procedure `usp_tsortiematiere_Insert`
--
DROP PROCEDURE IF EXISTS usp_tsortiematiere_Insert;

--
-- Drop procedure `usp_tsortiematiere_Select`
--
DROP PROCEDURE IF EXISTS usp_tsortiematiere_Select;

--
-- Drop procedure `usp_tsortiematiere_Update`
--
DROP PROCEDURE IF EXISTS usp_tsortiematiere_Update;

--
-- Drop table `tsortiematiere`
--
DROP TABLE IF EXISTS tsortiematiere;

--
-- Drop procedure `usp_tmatierepremiere_Delete`
--
DROP PROCEDURE IF EXISTS usp_tmatierepremiere_Delete;

--
-- Drop procedure `usp_tmatierepremiere_Insert`
--
DROP PROCEDURE IF EXISTS usp_tmatierepremiere_Insert;

--
-- Drop procedure `usp_tmatierepremiere_Select`
--
DROP PROCEDURE IF EXISTS usp_tmatierepremiere_Select;

--
-- Drop procedure `usp_tmatierepremiere_Update`
--
DROP PROCEDURE IF EXISTS usp_tmatierepremiere_Update;

--
-- Drop table `tmatierepremiere`
--
DROP TABLE IF EXISTS tmatierepremiere;

--
-- Drop view `v_presences`
--
DROP VIEW IF EXISTS v_presences CASCADE;

--
-- Drop table `tpresences`
--
DROP TABLE IF EXISTS tpresences;

--
-- Drop procedure `usp_tpersonnel_Delete`
--
DROP PROCEDURE IF EXISTS usp_tpersonnel_Delete;

--
-- Drop procedure `usp_tpersonnel_Insert`
--
DROP PROCEDURE IF EXISTS usp_tpersonnel_Insert;

--
-- Drop procedure `usp_tpersonnel_Select`
--
DROP PROCEDURE IF EXISTS usp_tpersonnel_Select;

--
-- Drop procedure `usp_tpersonnel_Update`
--
DROP PROCEDURE IF EXISTS usp_tpersonnel_Update;

--
-- Drop table `tpersonnel`
--
DROP TABLE IF EXISTS tpersonnel;

--
-- Drop procedure `usp_tsous_comptes_Delete`
--
DROP PROCEDURE IF EXISTS usp_tsous_comptes_Delete;

--
-- Drop procedure `usp_tsous_comptes_Insert`
--
DROP PROCEDURE IF EXISTS usp_tsous_comptes_Insert;

--
-- Drop procedure `usp_tsous_comptes_Select`
--
DROP PROCEDURE IF EXISTS usp_tsous_comptes_Select;

--
-- Drop procedure `usp_tsous_comptes_Update`
--
DROP PROCEDURE IF EXISTS usp_tsous_comptes_Update;

--
-- Drop table `tsous_comptes`
--
DROP TABLE IF EXISTS tsous_comptes;

--
-- Drop procedure `usp_tcomptes_Delete`
--
DROP PROCEDURE IF EXISTS usp_tcomptes_Delete;

--
-- Drop procedure `usp_tcomptes_Insert`
--
DROP PROCEDURE IF EXISTS usp_tcomptes_Insert;

--
-- Drop procedure `usp_tcomptes_Select`
--
DROP PROCEDURE IF EXISTS usp_tcomptes_Select;

--
-- Drop procedure `usp_tcomptes_Update`
--
DROP PROCEDURE IF EXISTS usp_tcomptes_Update;

--
-- Drop table `tcomptes`
--
DROP TABLE IF EXISTS tcomptes;

--
-- Drop procedure `usp_tmasse_bilantaire_Delete`
--
DROP PROCEDURE IF EXISTS usp_tmasse_bilantaire_Delete;

--
-- Drop procedure `usp_tmasse_bilantaire_Insert`
--
DROP PROCEDURE IF EXISTS usp_tmasse_bilantaire_Insert;

--
-- Drop procedure `usp_tmasse_bilantaire_Select`
--
DROP PROCEDURE IF EXISTS usp_tmasse_bilantaire_Select;

--
-- Drop procedure `usp_tmasse_bilantaire_Update`
--
DROP PROCEDURE IF EXISTS usp_tmasse_bilantaire_Update;

--
-- Drop table `tmasse_bilantaire`
--
DROP TABLE IF EXISTS tmasse_bilantaire;

--
-- Drop procedure `usp_tnature_compte_Delete`
--
DROP PROCEDURE IF EXISTS usp_tnature_compte_Delete;

--
-- Drop procedure `usp_tnature_compte_Insert`
--
DROP PROCEDURE IF EXISTS usp_tnature_compte_Insert;

--
-- Drop procedure `usp_tnature_compte_Select`
--
DROP PROCEDURE IF EXISTS usp_tnature_compte_Select;

--
-- Drop procedure `usp_tnature_compte_Update`
--
DROP PROCEDURE IF EXISTS usp_tnature_compte_Update;

--
-- Drop table `tnature_compte`
--
DROP TABLE IF EXISTS tnature_compte;

--
-- Set default database
--
USE db_pvc_renovee;

--
-- Create table `tnature_compte`
--
CREATE TABLE tnature_compte (
  id_nature int(11) NOT NULL AUTO_INCREMENT,
  nature_compte enum ('ACTIF', 'PASSIF', 'CHARGES', 'PRODUITS') NOT NULL,
  PRIMARY KEY (id_nature)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `usp_tnature_compte_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tnature_compte_Update (IN p_id_nature int,
IN p_nature_compte enum ('''ACTIF''', '''PASSIF''', '''CHARGES''', '''PRODUITS'''))
BEGIN
  START TRANSACTION;

    UPDATE tnature_compte
    SET nature_compte = p_nature_compte
    WHERE id_nature = p_id_nature;


    -- Begin Return row code block

    SELECT
      nature_compte
    FROM tnature_compte
    WHERE id_nature = p_id_nature;

  -- End Return row code block


  COMMIT;
END
$$

--
-- Create procedure `usp_tnature_compte_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tnature_compte_Select (IN p_id_nature int)
BEGIN
  START TRANSACTION;

    SELECT
      id_nature,
      nature_compte
    FROM tnature_compte
    ;

  COMMIT;
END
$$

--
-- Create procedure `usp_tnature_compte_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tnature_compte_Insert (IN p_nature_compte enum ('ACTIF', 'PASSIF', 'CHARGES', 'PRODUITS'))
BEGIN
  START TRANSACTION;

    INSERT INTO tnature_compte (nature_compte)
      VALUES (p_nature_compte);


    -- Begin Return row code block

    SELECT
      nature_compte
    FROM tnature_compte
    WHERE id_nature = LAST_INSERT_ID();

  -- End Return row code block


  COMMIT;
END
$$

--
-- Create procedure `usp_tnature_compte_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tnature_compte_Delete (p_id_nature int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tnature_compte
      WHERE id_nature = p_id_nature;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tmasse_bilantaire`
--
CREATE TABLE tmasse_bilantaire (
  id int(11) NOT NULL AUTO_INCREMENT,
  intitule varchar(200) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `usp_tmasse_bilantaire_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tmasse_bilantaire_Update (IN p_intitule varchar(200))
BEGIN
  DECLARE p_id int;
  SET p_id = (SELECT
      id
    FROM tmasse_bilantaire
    WHERE intitule = p_intitule);
  START TRANSACTION;

    UPDATE tmasse_bilantaire
    SET intitule = p_intitule
    WHERE id = p_id;


    -- Begin Return row code block

    SELECT
      intitule
    FROM tmasse_bilantaire
    WHERE id = p_id;

  -- End Return row code block


  COMMIT;
END
$$

--
-- Create procedure `usp_tmasse_bilantaire_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tmasse_bilantaire_Select (IN p_id int)
BEGIN
  START TRANSACTION;

    SELECT
      id,
      intitule
    FROM tmasse_bilantaire
    WHERE id = p_id;

  COMMIT;
END
$$

--
-- Create procedure `usp_tmasse_bilantaire_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tmasse_bilantaire_Insert (IN p_intitule varchar(200))
BEGIN
  START TRANSACTION;

    INSERT INTO tmasse_bilantaire (intitule)
      VALUES (p_intitule);


    -- Begin Return row code block

    SELECT
      intitule
    FROM tmasse_bilantaire
    WHERE id = LAST_INSERT_ID();

  -- End Return row code block


  COMMIT;
END
$$

--
-- Create procedure `usp_tmasse_bilantaire_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tmasse_bilantaire_Delete (p_intitule nvarchar(100))
BEGIN
  DECLARE p_id int;
  SET p_id = (SELECT
      id
    FROM tmasse_bilantaire
    WHERE intitule = p_intitule);
  START TRANSACTION;

    DELETE
      FROM tmasse_bilantaire
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tcomptes`
--
CREATE TABLE tcomptes (
  id int(11) NOT NULL AUTO_INCREMENT,
  numero varchar(6) NOT NULL,
  intitule varchar(100) NOT NULL,
  masse_bilantaire int(11) DEFAULT NULL,
  id_naturecompte int(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 17,
AVG_ROW_LENGTH = 1092,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `numero` on table `tcomptes`
--
ALTER TABLE tcomptes
ADD UNIQUE INDEX numero (numero);

--
-- Create foreign key
--
ALTER TABLE tcomptes
ADD CONSTRAINT tcomptes_ibfk_1 FOREIGN KEY (id_naturecompte)
REFERENCES tnature_compte (id_nature);

--
-- Create foreign key
--
ALTER TABLE tcomptes
ADD CONSTRAINT tcomptes_ibfk_2 FOREIGN KEY (masse_bilantaire)
REFERENCES tmasse_bilantaire (id) ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `usp_tcomptes_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tcomptes_Update (IN p_id int,
IN p_numero varchar(6),
IN p_intitule varchar(100),
IN p_classe_id int,
IN p_id_naturecompte int)
BEGIN
  START TRANSACTION;

    UPDATE tcomptes
    SET numero = p_numero,
        intitule = p_intitule,
        masse_bilantaire = p_classe_id,
        id_naturecompte = p_id_naturecompte
    WHERE id = p_id;


    -- Begin Return row code block

    SELECT
      numero,
      intitule,
      masse_bilantaire,
      id_naturecompte
    FROM tcomptes
    WHERE id = p_id;

  -- End Return row code block


  COMMIT;
END
$$

--
-- Create procedure `usp_tcomptes_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tcomptes_Select (IN p_id int)
BEGIN
  START TRANSACTION;

    SELECT
      id,
      numero,
      intitule,
      masse_bilantaire,
      id_naturecompte
    FROM tcomptes
    WHERE id = p_id;

  COMMIT;
END
$$

--
-- Create procedure `usp_tcomptes_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tcomptes_Insert (IN p_numero varchar(6),
IN p_intitule varchar(100),
IN p_masse_bilantaire nvarchar(100),
IN p_naturecompte nvarchar(100))
BEGIN
  DECLARE _id_masse_bilantaire int;
  DECLARE _id_naturecompte int;

  SET _id_masse_bilantaire = (SELECT
      id
    FROM tmasse_bilantaire
    WHERE intitule = p_masse_bilantaire);
  SET _id_naturecompte = (SELECT
      id_nature
    FROM tnature_compte
    WHERE nature_compte = p_naturecompte);
  START TRANSACTION;

    INSERT INTO tcomptes (numero, intitule, masse_bilantaire, id_naturecompte)
      VALUES (p_numero, p_intitule, _id_masse_bilantaire, _id_naturecompte);


    -- Begin Return row code block

    SELECT
      numero,
      intitule,
      masse_bilantaire,
      id_naturecompte
    FROM tcomptes
    WHERE id = LAST_INSERT_ID();

  -- End Return row code block


  COMMIT;
END
$$

--
-- Create procedure `usp_tcomptes_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tcomptes_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tcomptes
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tsous_comptes`
--
CREATE TABLE tsous_comptes (
  id int(11) NOT NULL AUTO_INCREMENT,
  numero varchar(15) NOT NULL,
  intitule varchar(200) NOT NULL,
  compte_id int(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `numero` on table `tsous_comptes`
--
ALTER TABLE tsous_comptes
ADD UNIQUE INDEX numero (numero);

--
-- Create foreign key
--
ALTER TABLE tsous_comptes
ADD CONSTRAINT tsous_comptes_ibfk_1 FOREIGN KEY (compte_id)
REFERENCES tcomptes (id);

DELIMITER $$

--
-- Create procedure `usp_tsous_comptes_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tsous_comptes_Update (IN p_id int,
IN p_numero varchar(15),
IN p_intitule varchar(200),
IN p_compte_id int)
BEGIN
  START TRANSACTION;

    UPDATE tsous_comptes
    SET numero = p_numero,
        intitule = p_intitule,
        compte_id = p_compte_id
    WHERE id = p_id;


    -- Begin Return row code block

    SELECT
      numero,
      intitule,
      compte_id
    FROM tsous_comptes
    WHERE id = p_id;

  -- End Return row code block


  COMMIT;
END
$$

--
-- Create procedure `usp_tsous_comptes_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tsous_comptes_Select (IN p_id int)
BEGIN
  START TRANSACTION;

    SELECT
      id,
      numero,
      intitule,
      compte_id
    FROM tsous_comptes;

  COMMIT;
END
$$

--
-- Create procedure `usp_tsous_comptes_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tsous_comptes_Insert (IN p_numero varchar(15),
IN p_intitule varchar(200),
IN p_compte_id int)
BEGIN
  START TRANSACTION;

    INSERT INTO tsous_comptes (numero, intitule, compte_id)
      VALUES (p_numero, p_intitule, p_compte_id);


    -- Begin Return row code block

    SELECT
      numero,
      intitule,
      compte_id
    FROM tsous_comptes
    WHERE id = LAST_INSERT_ID();

  -- End Return row code block


  COMMIT;
END
$$

--
-- Create procedure `usp_tsous_comptes_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tsous_comptes_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tsous_comptes
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tpersonnel`
--
CREATE TABLE tpersonnel (
  id int(11) NOT NULL AUTO_INCREMENT,
  nom varchar(100) DEFAULT NULL,
  postnom varchar(100) DEFAULT NULL,
  prenom varchar(100) DEFAULT NULL,
  numtelephon varchar(13) DEFAULT NULL,
  adresse varchar(100) DEFAULT NULL,
  statut tinyint(1) DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `usp_tpersonnel_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tpersonnel_Update (IN p_id int,
IN p_nom varchar(100),
IN p_postnom varchar(100),
IN p_prenom varchar(100),
IN p_numtelephon varchar(13),
IN p_adresse varchar(100),
IN p_statut tinyint(1))
BEGIN
  START TRANSACTION;

    UPDATE tpersonnel
    SET nom = p_nom,
        postnom = p_postnom,
        prenom = p_prenom,
        numtelephon = p_numtelephon,
        adresse = p_adresse,
        statut = p_statut
    WHERE id = p_id;

  /*
  -- Begin Return row code block

  SELECT nom, postnom, prenom, numtelephon, adresse, statut
  FROM   tpersonnel
  WHERE  id = p_id;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tpersonnel_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tpersonnel_Select ()
BEGIN
  START TRANSACTION;

    SELECT
      id AS Num,
      CONCAT(nom, ' ', postnom, ' ', prenom) AS Noms,
      numtelephon AS Num_Telephone,
      adresse AS Adresse
    FROM tpersonnel;

  COMMIT;
END
$$

--
-- Create procedure `usp_tpersonnel_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tpersonnel_Insert (IN p_nom varchar(100),
IN p_postnom varchar(100),
IN p_prenom varchar(100),
IN p_numtelephon varchar(13),
IN p_adresse varchar(100),
IN p_statut tinyint(1))
BEGIN
  START TRANSACTION;

    INSERT INTO tpersonnel (nom, postnom, prenom, numtelephon, adresse, statut)
      VALUES (p_nom, p_postnom, p_prenom, p_numtelephon, p_adresse, p_statut);

  /*
  -- Begin Return row code block

  SELECT nom, postnom, prenom, numtelephon, adresse, statut
  FROM   tpersonnel
  WHERE  id = LAST_INSERT_ID();

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tpersonnel_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tpersonnel_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tpersonnel
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tpresences`
--
CREATE TABLE tpresences (
  id int(11) NOT NULL AUTO_INCREMENT,
  id_agent int(11) DEFAULT NULL,
  heure_arrivee datetime DEFAULT NULL,
  heure_sortie datetime DEFAULT NULL,
  est_ferie tinyint(1) DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tpresences
ADD CONSTRAINT tpresences_ibfk_1 FOREIGN KEY (id_agent)
REFERENCES tpersonnel (id);

--
-- Create view `v_presences`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_presences
AS
SELECT
  `p`.`id` AS `id_presence`,
  `pers`.`nom` AS `nom`,
  `pers`.`postnom` AS `postnom`,
  `pers`.`prenom` AS `prenom`,
  `p`.`heure_arrivee` AS `heure_arrivee`,
  `p`.`heure_sortie` AS `heure_sortie`,
  `p`.`est_ferie` AS `est_ferie`
FROM (`tpresences` `p`
  JOIN `tpersonnel` `pers`
    ON (`p`.`id_agent` = `pers`.`id`))
ORDER BY `p`.`heure_arrivee` DESC;

--
-- Create table `tmatierepremiere`
--
CREATE TABLE tmatierepremiere (
  id int(11) NOT NULL AUTO_INCREMENT,
  reference varchar(50) NOT NULL,
  designation varchar(100) NOT NULL,
  unite_mesure enum ('PIECE', 'KG', 'Litre', 'Sac', 'Boite', 'Carton') DEFAULT 'PIECE',
  stock_actuel decimal(10, 2) DEFAULT 0.00,
  cmup decimal(10, 2) DEFAULT 0.00,
  seuil_reappro decimal(10, 2) DEFAULT 0.00,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `usp_tmatierepremiere_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tmatierepremiere_Update (IN p_id int,
IN p_reference varchar(50),
IN p_designation varchar(100),
IN p_unite_mesure enum ('''PIECE''', '''KG''', '''Litre''', '''Sac''', '''Boite''', '''Carton'''),
IN p_stock_actuel decimal(10, 2),
IN p_cmup decimal(10, 2),
IN p_seuil_reappro decimal(10, 2))
BEGIN
  START TRANSACTION;

    UPDATE tmatierepremiere
    SET reference = p_reference,
        designation = p_designation,
        unite_mesure = p_unite_mesure,
        stock_actuel = p_stock_actuel,
        cmup = p_cmup,
        seuil_reappro = p_seuil_reappro
    WHERE id = p_id;

  /*
  -- Begin Return row code block

  SELECT reference, designation, unite_mesure, stock_actuel, cmup, seuil_reappro
  FROM   tmatierepremiere
  WHERE  id = p_id;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tmatierepremiere_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tmatierepremiere_Select (IN p_id int)
BEGIN
  START TRANSACTION;

    SELECT
      id,
      reference,
      designation,
      unite_mesure,
      stock_actuel,
      cmup,
      seuil_reappro
    FROM tmatierepremiere
    WHERE id = p_id;

  COMMIT;
END
$$

--
-- Create procedure `usp_tmatierepremiere_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tmatierepremiere_Insert (IN p_reference varchar(50),
IN p_designation varchar(100),
IN p_unite_mesure enum ('PIECE', 'KG', 'Litre', 'Sac', 'Boite', 'Carton'),
IN p_stock_actuel decimal(10, 2),
IN p_cmup decimal(10, 2),
IN p_seuil_reappro decimal(10, 2))
BEGIN
  START TRANSACTION;

    INSERT INTO tmatierepremiere (reference, designation, unite_mesure, stock_actuel, cmup, seuil_reappro)
      VALUES (p_reference, p_designation, p_unite_mesure, p_stock_actuel, p_cmup, p_seuil_reappro);

  /*
  -- Begin Return row code block

  SELECT reference, designation, unite_mesure, stock_actuel, cmup, seuil_reappro
  FROM   tmatierepremiere
  WHERE  id = LAST_INSERT_ID();

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tmatierepremiere_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tmatierepremiere_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tmatierepremiere
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tsortiematiere`
--
CREATE TABLE tsortiematiere (
  id int(11) NOT NULL AUTO_INCREMENT,
  date_sortie date NOT NULL,
  matiere_premiere_id int(11) DEFAULT NULL,
  quantite decimal(10, 2) NOT NULL,
  unite varchar(20) DEFAULT 'PIECE',
  cout_unitaire decimal(10, 2) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tsortiematiere
ADD CONSTRAINT tsortiematiere_ibfk_1 FOREIGN KEY (matiere_premiere_id)
REFERENCES tmatierepremiere (id);

DELIMITER $$

--
-- Create procedure `usp_tsortiematiere_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tsortiematiere_Update (IN p_id int,
IN p_date_sortie date,
IN p_matiere_premiere_id int,
IN p_quantite decimal(10, 2),
IN p_unite varchar(20),
IN p_cout_unitaire decimal(10, 2))
BEGIN
  START TRANSACTION;

    UPDATE tsortiematiere
    SET date_sortie = p_date_sortie,
        matiere_premiere_id = p_matiere_premiere_id,
        quantite = p_quantite,
        unite = p_unite,
        cout_unitaire = p_cout_unitaire
    WHERE id = p_id;

  /*
  -- Begin Return row code block

  SELECT date_sortie, matiere_premiere_id, quantite, unite, cout_unitaire
  FROM   tsortiematiere
  WHERE  id = p_id;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tsortiematiere_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tsortiematiere_Select (IN p_id int)
BEGIN
  START TRANSACTION;

    SELECT
      id,
      date_sortie,
      matiere_premiere_id,
      quantite,
      unite,
      cout_unitaire
    FROM tsortiematiere
    WHERE id = p_id;

  COMMIT;
END
$$

--
-- Create procedure `usp_tsortiematiere_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tsortiematiere_Insert (IN p_date_sortie date,
IN p_matiere_premiere_id int,
IN p_quantite decimal(10, 2),
IN p_unite varchar(20),
IN p_cout_unitaire decimal(10, 2))
BEGIN
  START TRANSACTION;

    INSERT INTO tsortiematiere (date_sortie, matiere_premiere_id, quantite, unite, cout_unitaire)
      VALUES (p_date_sortie, p_matiere_premiere_id, p_quantite, p_unite, p_cout_unitaire);

  /*
  -- Begin Return row code block

  SELECT date_sortie, matiere_premiere_id, quantite, unite, cout_unitaire
  FROM   tsortiematiere
  WHERE  id = LAST_INSERT_ID();

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tsortiematiere_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tsortiematiere_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tsortiematiere
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tclient`
--
CREATE TABLE tclient (
  id int(11) NOT NULL AUTO_INCREMENT,
  code varchar(50) NOT NULL,
  raison_sociale varchar(100) NOT NULL,
  adresse varchar(255) DEFAULT NULL,
  conditions_paiement varchar(100) DEFAULT NULL,
  solde_compte decimal(10, 2) DEFAULT 0.00,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `tventeproduitfini`
--
CREATE TABLE tventeproduitfini (
  id int(11) NOT NULL AUTO_INCREMENT,
  date_vente date NOT NULL,
  client_id int(11) DEFAULT NULL,
  montant_total_vente decimal(10, 2) NOT NULL,
  montant_payee decimal(10, 2) NOT NULL,
  type_paiement enum ('CASH', 'CREDIT', 'ANTICIPATION') NOT NULL,
  etat_paiement enum ('payé', 'non payé') DEFAULT 'non payé',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tventeproduitfini
ADD CONSTRAINT tventeproduitfini_ibfk_1 FOREIGN KEY (client_id)
REFERENCES tclient (id);

DELIMITER $$

--
-- Create procedure `usp_tventeproduitfini_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tventeproduitfini_Update (IN p_id int,
IN p_date_vente date,
IN p_client_id int,
IN p_montant_total_vente decimal(10, 2),
IN p_montant_payee decimal(10, 2),
IN p_type_paiement enum ('''CASH''', '''CREDIT''', '''ANTICIPATION'''),
IN p_etat_paiement enum ('''payé''', '''non payé'''))
BEGIN
  START TRANSACTION;

    UPDATE tventeproduitfini
    SET date_vente = p_date_vente,
        client_id = p_client_id,
        montant_total_vente = p_montant_total_vente,
        montant_payee = p_montant_payee,
        type_paiement = p_type_paiement,
        etat_paiement = p_etat_paiement
    WHERE id = p_id;

  /*
  -- Begin Return row code block

  SELECT date_vente, client_id, montant_total_vente, montant_payee, type_paiement, etat_paiement
  FROM   tventeproduitfini
  WHERE  id = p_id;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tventeproduitfini_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tventeproduitfini_Select (IN p_id int)
BEGIN
  START TRANSACTION;

    SELECT
      id,
      date_vente,
      client_id,
      montant_total_vente,
      montant_payee,
      type_paiement,
      etat_paiement
    FROM tventeproduitfini
    WHERE id = p_id;

  COMMIT;
END
$$

--
-- Create procedure `usp_tventeproduitfini_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tventeproduitfini_Insert (IN p_date_vente date,
IN p_client_id int,
IN p_montant_total_vente decimal(10, 2),
IN p_montant_payee decimal(10, 2),
IN p_type_paiement enum ('''CASH''', '''CREDIT''', '''ANTICIPATION'''),
IN p_etat_paiement enum ('''payé''', '''non payé'''))
BEGIN
  START TRANSACTION;

    INSERT INTO tventeproduitfini (date_vente, client_id, montant_total_vente, montant_payee, type_paiement,
    etat_paiement)
      VALUES (p_date_vente, p_client_id, p_montant_total_vente, p_montant_payee, p_type_paiement, p_etat_paiement);

  /*
  -- Begin Return row code block

  SELECT date_vente, client_id, montant_total_vente, montant_payee, type_paiement, etat_paiement
  FROM   tventeproduitfini
  WHERE  id = LAST_INSERT_ID();

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tventeproduitfini_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tventeproduitfini_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tventeproduitfini
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create view `v_ventes_clients`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_ventes_clients
AS
SELECT
  `v`.`id` AS `id_vente`,
  `v`.`date_vente` AS `date_vente`,
  `c`.`raison_sociale` AS `client`,
  `v`.`montant_total_vente` AS `montant_total_vente`,
  `v`.`montant_payee` AS `montant_payee`,
  `v`.`type_paiement` AS `type_paiement`,
  `v`.`etat_paiement` AS `etat_paiement`
FROM (`tventeproduitfini` `v`
  LEFT JOIN `tclient` `c`
    ON (`v`.`client_id` = `c`.`id`))
ORDER BY `v`.`date_vente` DESC;

--
-- Create view `v_balance_agee_clients`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_balance_agee_clients
AS
SELECT
  `c`.`id` AS `client_id`,
  `c`.`raison_sociale` AS `client`,
  `v`.`date_vente` AS `date_vente`,
  `v`.`montant_total_vente` AS `montant_total_vente`,
  `v`.`montant_payee` AS `montant_payee`,
  `v`.`montant_total_vente` - `v`.`montant_payee` AS `solde_du`,
  TO_DAYS(CURDATE()) - TO_DAYS(`v`.`date_vente`) AS `jours_retard`,
  CASE WHEN TO_DAYS(CURDATE()) - TO_DAYS(`v`.`date_vente`) <= 30 THEN '0-30 jours' WHEN TO_DAYS(CURDATE()) - TO_DAYS(`v`.`date_vente`) BETWEEN 31 AND 60 THEN '31-60 jours' WHEN TO_DAYS(CURDATE()) - TO_DAYS(`v`.`date_vente`) BETWEEN 61 AND 90 THEN '61-90 jours' ELSE '+90 jours' END AS `tranche_age`
FROM (`tventeproduitfini` `v`
  JOIN `tclient` `c`
    ON (`v`.`client_id` = `c`.`id`))
WHERE `v`.`montant_total_vente` - `v`.`montant_payee` > 0
ORDER BY CASE WHEN TO_DAYS(CURDATE()) - TO_DAYS(`v`.`date_vente`) <= 30 THEN '0-30 jours' WHEN TO_DAYS(CURDATE()) - TO_DAYS(`v`.`date_vente`) BETWEEN 31 AND 60 THEN '31-60 jours' WHEN TO_DAYS(CURDATE()) - TO_DAYS(`v`.`date_vente`) BETWEEN 61 AND 90 THEN '61-90 jours' ELSE '+90 jours' END, `v`.`date_vente`;

--
-- Create table `tpaiements_clients`
--
CREATE TABLE tpaiements_clients (
  id_paiement int(11) NOT NULL AUTO_INCREMENT,
  id_client int(11) DEFAULT NULL,
  id_vente int(11) DEFAULT NULL,
  date_paiement timestamp NULL DEFAULT CURRENT_TIMESTAMP(),
  libelle varchar(200) NOT NULL,
  montant_paye decimal(10, 2) NOT NULL,
  um enum ('USD', 'CDF') DEFAULT 'USD',
  type_paiement enum ('Comptant', 'Crédit', 'Anticipation') NOT NULL,
  statut_paiement enum ('Réglé', 'Partiel', 'Annulé') DEFAULT 'Réglé',
  PRIMARY KEY (id_paiement)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tpaiements_clients
ADD CONSTRAINT tpaiements_clients_ibfk_1 FOREIGN KEY (id_client)
REFERENCES tclient (id);

--
-- Create foreign key
--
ALTER TABLE tpaiements_clients
ADD CONSTRAINT tpaiements_clients_ibfk_2 FOREIGN KEY (id_vente)
REFERENCES tventeproduitfini (id);

DELIMITER $$

--
-- Create procedure `usp_tpaiements_clients_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tpaiements_clients_Update (IN p_id_paiement int,
IN p_id_client int,
IN p_id_vente int,
IN p_date_paiement timestamp,
IN p_libelle varchar(200),
IN p_montant_paye decimal(10, 2),
IN p_um enum ('''USD''', '''CDF'''),
IN p_type_paiement enum ('''Comptant''', '''Crédit''', '''Anticipation'''),
IN p_statut_paiement enum ('''Réglé''', '''Partiel''', '''Annulé'''))
BEGIN
  START TRANSACTION;

    UPDATE tpaiements_clients
    SET id_client = p_id_client,
        id_vente = p_id_vente,
        date_paiement = p_date_paiement,
        libelle = p_libelle,
        montant_paye = p_montant_paye,
        um = p_um,
        type_paiement = p_type_paiement,
        statut_paiement = p_statut_paiement
    WHERE id_paiement = p_id_paiement;

  /*
  -- Begin Return row code block

  SELECT id_client, id_vente, date_paiement, libelle, montant_paye, um, type_paiement, statut_paiement
  FROM   tpaiements_clients
  WHERE  id_paiement = p_id_paiement;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tpaiements_clients_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tpaiements_clients_Select (IN p_id_paiement int)
BEGIN
  START TRANSACTION;

    SELECT
      id_paiement,
      id_client,
      id_vente,
      date_paiement,
      libelle,
      montant_paye,
      um,
      type_paiement,
      statut_paiement
    FROM tpaiements_clients
    WHERE id_paiement = p_id_paiement;

  COMMIT;
END
$$

--
-- Create procedure `usp_tpaiements_clients_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tpaiements_clients_Insert (IN p_id_client int,
IN p_id_vente int,
IN p_date_paiement timestamp,
IN p_libelle varchar(200),
IN p_montant_paye decimal(10, 2),
IN p_um enum ('''USD''', '''CDF'''),
IN p_type_paiement enum ('''Comptant''', '''Crédit''', '''Anticipation'''),
IN p_statut_paiement enum ('''Réglé''', '''Partiel''', '''Annulé'''))
BEGIN
  START TRANSACTION;

    INSERT INTO tpaiements_clients (id_client, id_vente, date_paiement, libelle, montant_paye, um, type_paiement,
    statut_paiement)
      VALUES (p_id_client, p_id_vente, p_date_paiement, p_libelle, p_montant_paye, p_um, p_type_paiement,
      p_statut_paiement);

  /*
  -- Begin Return row code block

  SELECT id_client, id_vente, date_paiement, libelle, montant_paye, um, type_paiement, statut_paiement
  FROM   tpaiements_clients
  WHERE  id_paiement = LAST_INSERT_ID();

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tpaiements_clients_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tpaiements_clients_Delete (p_id_paiement int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tpaiements_clients
      WHERE id_paiement = p_id_paiement;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tcommandeclient`
--
CREATE TABLE tcommandeclient (
  id int(11) NOT NULL AUTO_INCREMENT,
  numero varchar(50) NOT NULL,
  date_commande date NOT NULL,
  client_id int(11) DEFAULT NULL,
  date_livraison_prevue date DEFAULT NULL,
  statut enum ('en attente', 'livrée', 'annulée') DEFAULT 'en attente',
  montant_tot decimal(10, 2) NOT NULL,
  montant_anticipation decimal(10, 2) DEFAULT 0.00,
  date_paiement_anticipation date DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tcommandeclient
ADD CONSTRAINT tcommandeclient_ibfk_1 FOREIGN KEY (client_id)
REFERENCES tclient (id);

DELIMITER $$

--
-- Create procedure `usp_tcommandeclient_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tcommandeclient_Update (IN p_id int,
IN p_numero varchar(50),
IN p_date_commande date,
IN p_client_id int,
IN p_date_livraison_prevue date,
IN p_statut enum ('''en attente''', '''livrée''', '''annulée'''),
IN p_montant_tot decimal(10, 2),
IN p_montant_anticipation decimal(10, 2),
IN p_date_paiement_anticipation date)
BEGIN
  START TRANSACTION;

    UPDATE tcommandeclient
    SET numero = p_numero,
        date_commande = p_date_commande,
        client_id = p_client_id,
        date_livraison_prevue = p_date_livraison_prevue,
        statut = p_statut,
        montant_tot = p_montant_tot,
        montant_anticipation = p_montant_anticipation,
        date_paiement_anticipation = p_date_paiement_anticipation
    WHERE id = p_id;

  /*
  -- Begin Return row code block

  SELECT numero, date_commande, client_id, date_livraison_prevue, statut, montant_tot, montant_anticipation,
         date_paiement_anticipation
  FROM   tcommandeclient
  WHERE  id = p_id;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tcommandeclient_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tcommandeclient_Select ()
BEGIN
  START TRANSACTION;

    SELECT
      id,
      numero,
      date_commande,
      t.raison_sociale,
      date_livraison_prevue,
      statut,
      montant_tot,
      montant_anticipation,
      date_paiement_anticipation
    FROM tcommandeclient
      INNER JOIN tclient t
        ON tcommandeclient.client_id = t.id
    ;

  COMMIT;
END
$$

--
-- Create procedure `usp_tcommandeclient_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tcommandeclient_Insert (IN p_numero varchar(50),
IN p_date_commande date,
IN p_client_id int,
IN p_date_livraison_prevue date,
IN p_statut enum ('''en attente''', '''livrée''', '''annulée'''),
IN p_montant_tot decimal(10, 2),
IN p_montant_anticipation decimal(10, 2),
IN p_date_paiement_anticipation date)
BEGIN
  START TRANSACTION;

    INSERT INTO tcommandeclient (numero, date_commande, client_id, date_livraison_prevue, statut, montant_tot,
    montant_anticipation, date_paiement_anticipation)
      VALUES (p_numero, p_date_commande, p_client_id, p_date_livraison_prevue, p_statut, p_montant_tot,
      p_montant_anticipation, p_date_paiement_anticipation);

  /*
  -- Begin Return row code block

  SELECT numero, date_commande, client_id, date_livraison_prevue, statut, montant_tot, montant_anticipation,
         date_paiement_anticipation
  FROM   tcommandeclient
  WHERE  id = LAST_INSERT_ID();

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tcommandeclient_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tcommandeclient_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tcommandeclient
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tmateriels`
--
CREATE TABLE tmateriels (
  id_materiel int(11) NOT NULL AUTO_INCREMENT,
  code_materiel varchar(50) NOT NULL,
  designation varchar(100) NOT NULL,
  date_acquisition date NOT NULL,
  valeur_acquisition decimal(15, 2) NOT NULL,
  amortissable tinyint(1) DEFAULT 1,
  taux_amortissement decimal(5, 2) NOT NULL,
  mode_amortissement enum ('lineaire', 'degressif') NOT NULL,
  periodicite enum ('Mensuel', 'Annuel') DEFAULT 'Mensuel',
  duree_utilisation int(11) NOT NULL,
  valeur_residuelle decimal(15, 2) DEFAULT 0.00,
  provenance varchar(100) DEFAULT NULL,
  statut enum ('en service', 'en maintenance', 'hors service', 'vendu') DEFAULT 'en service',
  Coefficient_degressif varchar(255) DEFAULT NULL,
  column1 int(11) DEFAULT NULL,
  PRIMARY KEY (id_materiel)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `code_materiel` on table `tmateriels`
--
ALTER TABLE tmateriels
ADD UNIQUE INDEX code_materiel (code_materiel);

--
-- Create table `tplan_amortissements`
--
CREATE TABLE tplan_amortissements (
  id_amort int(11) NOT NULL AUTO_INCREMENT,
  id_materiel int(11) NOT NULL,
  date_calcul date NOT NULL,
  valeur_base decimal(15, 2) NOT NULL,
  taux decimal(15, 2) NOT NULL,
  duree decimal(15, 2) NOT NULL,
  mensualite decimal(15, 2) NOT NULL,
  annuite decimal(15, 2) NOT NULL,
  amort_cumule decimal(15, 2) NOT NULL,
  valeur_nette decimal(15, 2) NOT NULL,
  PRIMARY KEY (id_amort)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tplan_amortissements
ADD CONSTRAINT tplan_amortissements_ibfk_1 FOREIGN KEY (id_materiel)
REFERENCES tmateriels (id_materiel);

DELIMITER $$

--
-- Create procedure `pr_insert_plan_amort`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE pr_insert_plan_amort (IN _id_materiel int,
IN _date_amort date,
IN _valeur_base decimal(15, 2),
IN _taux decimal(15, 2),
IN _periodicite varchar(20),
IN _duree decimal(15, 2),
IN _valeur_nette decimal(15, 2),
IN _mode_amort varchar(40),
IN _Coefficient_degressif int)
BEGIN
  DECLARE _valeur_base2 decimal(15, 2);
  DECLARE _mensualite decimal(10, 2);
  DECLARE _annuite decimal(10, 2);
  DECLARE _amort_cumule decimal(10, 2) DEFAULT 0;
  DECLARE _valeur_nette2 decimal(15, 2);
  DECLARE _date_calc date;
  DECLARE i int DEFAULT 1;

  -- Initialisation des valeurs
  SET _valeur_nette2 = _valeur_nette;
  SET _valeur_base2 = _valeur_base;
  SET _date_calc = _date_amort;

  -- Boucle pour générer le plan
  WHILE i <= _duree DO

    -- Mise à jour de la date en fonction de la périodicité
    IF (_periodicite = 'Mensuel') THEN
      SET _date_calc = LAST_DAY(DATE_ADD(_date_amort, INTERVAL i MONTH));
    ELSEIF (_periodicite = 'Annuel') THEN
      -- Fixer la date de calcul au 31 décembre de chaque année
      SET _date_calc = STR_TO_DATE(CONCAT(YEAR(_date_amort) + i, '-12-31'), '%Y-%m-%d');
    END IF;

    -- Calcul des montants d'amortissement
    IF (_mode_amort = 'lineaire') THEN
      SET _annuite = (_valeur_base / _duree);
      SET _mensualite = _annuite / 12;
    ELSEIF (_mode_amort = 'degressif') THEN
      SET _annuite = (_valeur_base2 * (100 / _duree) * _Coefficient_degressif);
      SET _mensualite = (_valeur_base2 * (100 / _duree) * _Coefficient_degressif) / 12;
    END IF;

    -- Mise à jour des cumuls
    SET _amort_cumule = _amort_cumule + _mensualite;
    SET _valeur_nette2 = _valeur_base - _amort_cumule;

    -- Insertion dans le plan d'amortissement
    INSERT INTO tplan_amortissements (id_materiel,
    date_calcul,
    valeur_base,
    taux,
    duree,
    mensualite,
    annuite,
    amort_cumule,
    valeur_nette)
      VALUES
      (
      _id_materiel,
      _date_calc,
      _valeur_base2,
      _taux,
      _duree,
      _mensualite,
      _annuite,
      _amort_cumule,
      _valeur_nette2
      );

    -- Préparation pour l'itération suivante
    SET _valeur_base2 = _valeur_nette2;
    SET i = i + 1;
  END WHILE;

  -- Retour de confirmation
  SELECT
    CONCAT('Plan d''amortissement généré pour le matériel ID : ', _id_materiel) AS Message;

END
$$

DELIMITER ;

--
-- Create view `v_plan_amortissement`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_plan_amortissement
AS
SELECT
  `m`.`id_materiel` AS `id_materiel`,
  `m`.`code_materiel` AS `code_materiel`,
  `m`.`designation` AS `designation`,
  `m`.`date_acquisition` AS `date_acquisition`,
  `m`.`valeur_acquisition` AS `valeur_acquisition`,
  `m`.`taux_amortissement` AS `taux_amortissement`,
  `m`.`mode_amortissement` AS `mode_amortissement`,
  `p`.`date_calcul` AS `date_calcul`,
  `p`.`mensualite` AS `mensualite`,
  `p`.`annuite` AS `annuite`,
  `p`.`amort_cumule` AS `amort_cumule`,
  `p`.`valeur_nette` AS `valeur_nette`
FROM (`tmateriels` `m`
  JOIN `tplan_amortissements` `p`
    ON (`m`.`id_materiel` = `p`.`id_materiel`))
ORDER BY `m`.`id_materiel`, `p`.`date_calcul`;

--
-- Create table `tpostes`
--
CREATE TABLE tpostes (
  id int(11) NOT NULL AUTO_INCREMENT,
  nom_poste varchar(100) DEFAULT NULL,
  salaire_mensuel decimal(10, 2) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `taffectations_personnel`
--
CREATE TABLE taffectations_personnel (
  id int(11) NOT NULL AUTO_INCREMENT,
  id_perso int(11) DEFAULT NULL,
  poste_id int(11) DEFAULT NULL,
  date_affectation date DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE taffectations_personnel
ADD CONSTRAINT taffectations_personnel_ibfk_1 FOREIGN KEY (id_perso)
REFERENCES tpersonnel (id);

--
-- Create foreign key
--
ALTER TABLE taffectations_personnel
ADD CONSTRAINT taffectations_personnel_ibfk_2 FOREIGN KEY (poste_id)
REFERENCES tpostes (id);

--
-- Create view `v_paie_personnel`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_paie_personnel
AS
SELECT
  `pers`.`id` AS `id_agent`,
  CONCAT(`pers`.`nom`, ' ', `pers`.`postnom`, ' ', `pers`.`prenom`) AS `agent`,
  `pos`.`nom_poste` AS `nom_poste`,
  `pos`.`salaire_mensuel` AS `salaire_mensuel`,
  `pers`.`statut` AS `statut`
FROM ((`tpersonnel` `pers`
  LEFT JOIN `taffectations_personnel` `aff`
    ON (`pers`.`id` = `aff`.`id_perso`))
  LEFT JOIN `tpostes` `pos`
    ON (`aff`.`poste_id` = `pos`.`id`))
ORDER BY CONCAT(`pers`.`nom`, ' ', `pers`.`postnom`, ' ', `pers`.`prenom`);

--
-- Create table `tagent_achat`
--
CREATE TABLE tagent_achat (
  id int(11) NOT NULL AUTO_INCREMENT,
  code varchar(50) NOT NULL,
  nom varchar(100) NOT NULL,
  postnom varchar(100) NOT NULL,
  prenom varchar(100) NOT NULL,
  adresse varchar(255) DEFAULT NULL,
  tel varchar(20) DEFAULT NULL,
  email varchar(100) DEFAULT NULL,
  solde_compte decimal(10, 2) DEFAULT 0.00,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `tentreematiere`
--
CREATE TABLE tentreematiere (
  id int(11) NOT NULL AUTO_INCREMENT,
  date_entree date NOT NULL,
  matiere_premiere_id int(11) DEFAULT NULL,
  agent_achat_id int(11) DEFAULT NULL,
  quantite decimal(10, 2) NOT NULL,
  unite varchar(20) DEFAULT 'PIECE',
  prix_unitaire_entree decimal(10, 2) NOT NULL,
  montant_payer decimal(10, 2) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tentreematiere
ADD CONSTRAINT tentreematiere_ibfk_1 FOREIGN KEY (matiere_premiere_id)
REFERENCES tmatierepremiere (id);

--
-- Create foreign key
--
ALTER TABLE tentreematiere
ADD CONSTRAINT tentreematiere_ibfk_2 FOREIGN KEY (agent_achat_id)
REFERENCES tagent_achat (id);

DELIMITER $$

--
-- Create procedure `usp_tentreematiere_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tentreematiere_Update (IN p_id int,
IN p_date_entree date,
IN p_matiere_premiere_id int,
IN p_agent_achat_id int,
IN p_quantite decimal(10, 2),
IN p_unite varchar(20),
IN p_prix_unitaire_entree decimal(10, 2),
IN p_montant_payer decimal(10, 2))
BEGIN
  START TRANSACTION;

    UPDATE tentreematiere
    SET date_entree = p_date_entree,
        matiere_premiere_id = p_matiere_premiere_id,
        agent_achat_id = p_agent_achat_id,
        quantite = p_quantite,
        unite = p_unite,
        prix_unitaire_entree = p_prix_unitaire_entree,
        montant_payer = p_montant_payer
    WHERE id = p_id;

  /*
  -- Begin Return row code block

  SELECT date_entree, matiere_premiere_id, agent_achat_id, quantite, unite, prix_unitaire_entree,
         montant_payer
  FROM   tentreematiere
  WHERE  id = p_id;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tentreematiere_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tentreematiere_Select (IN p_id int)
BEGIN
  START TRANSACTION;

    SELECT
      id,
      date_entree,
      matiere_premiere_id,
      agent_achat_id,
      quantite,
      unite,
      prix_unitaire_entree,
      montant_payer
    FROM tentreematiere
    WHERE id = p_id;

  COMMIT;
END
$$

--
-- Create procedure `usp_tentreematiere_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tentreematiere_Insert (IN p_date_entree date,
IN p_matiere_premiere_id int,
IN p_agent_achat_id int,
IN p_quantite decimal(10, 2),
IN p_unite varchar(20),
IN p_prix_unitaire_entree decimal(10, 2),
IN p_montant_payer decimal(10, 2))
BEGIN
  START TRANSACTION;

    INSERT INTO tentreematiere (date_entree, matiere_premiere_id, agent_achat_id, quantite, unite, prix_unitaire_entree,
    montant_payer)
      VALUES (p_date_entree, p_matiere_premiere_id, p_agent_achat_id, p_quantite, p_unite, p_prix_unitaire_entree,
      p_montant_payer);

  /*
  -- Begin Return row code block

  SELECT date_entree, matiere_premiere_id, agent_achat_id, quantite, unite, prix_unitaire_entree,
         montant_payer
  FROM   tentreematiere
  WHERE  id = LAST_INSERT_ID();

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tentreematiere_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tentreematiere_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tentreematiere
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create view `v_stock_matiere`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_stock_matiere
AS
SELECT
  `mp`.`id` AS `id_matiere`,
  `mp`.`reference` AS `reference`,
  `mp`.`designation` AS `designation`,
  `mp`.`stock_actuel` AS `stock_actuel`,
  COALESCE(SUM(`ent`.`quantite`), 0) AS `total_entrees`,
  COALESCE(SUM(`sort`.`quantite`), 0) AS `total_sorties`
FROM ((`tmatierepremiere` `mp`
  LEFT JOIN `tentreematiere` `ent`
    ON (`mp`.`id` = `ent`.`matiere_premiere_id`))
  LEFT JOIN `tsortiematiere` `sort`
    ON (`mp`.`id` = `sort`.`matiere_premiere_id`))
GROUP BY `mp`.`id`,
         `mp`.`reference`,
         `mp`.`designation`,
         `mp`.`stock_actuel`;

--
-- Create view `v_balance_agee_fournisseurs`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_balance_agee_fournisseurs
AS
SELECT
  `f`.`id` AS `id_agent`,
  CONCAT(`f`.`nom`, ' ', `f`.`postnom`, ' ', `f`.`prenom`) AS `Agent_achat`,
  `ach`.`date_entree` AS `date_entree`,
  `ach`.`quantite` * `ach`.`prix_unitaire_entree` AS `montant_total`,
  `ach`.`montant_payer` AS `montant_payer`,
  `ach`.`quantite` * `ach`.`prix_unitaire_entree` - `ach`.`montant_payer` AS `solde_du`,
  TO_DAYS(CURDATE()) - TO_DAYS(`ach`.`date_entree`) AS `jours_retard`,
  CASE WHEN TO_DAYS(CURDATE()) - TO_DAYS(`ach`.`date_entree`) <= 30 THEN '0-30 jours' WHEN TO_DAYS(CURDATE()) - TO_DAYS(`ach`.`date_entree`) BETWEEN 31 AND 60 THEN '31-60 jours' WHEN TO_DAYS(CURDATE()) - TO_DAYS(`ach`.`date_entree`) BETWEEN 61 AND 90 THEN '61-90 jours' ELSE '+90 jours' END AS `tranche_age`
FROM (`tentreematiere` `ach`
  JOIN `tagent_achat` `f`
    ON (`ach`.`id` = `f`.`id`))
WHERE `ach`.`quantite` * `ach`.`prix_unitaire_entree` - `ach`.`montant_payer` > 0
ORDER BY CASE WHEN TO_DAYS(CURDATE()) - TO_DAYS(`ach`.`date_entree`) <= 30 THEN '0-30 jours' WHEN TO_DAYS(CURDATE()) - TO_DAYS(`ach`.`date_entree`) BETWEEN 31 AND 60 THEN '31-60 jours' WHEN TO_DAYS(CURDATE()) - TO_DAYS(`ach`.`date_entree`) BETWEEN 61 AND 90 THEN '61-90 jours' ELSE '+90 jours' END, `ach`.`date_entree`;

--
-- Create view `v_balance_agee_consolide`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_balance_agee_consolide
AS
SELECT
  `c`.`id` AS `client_id`,
  `c`.`raison_sociale` AS `client`,
  `v`.`date_vente` AS `date_vente`,
  `v`.`montant_total_vente` AS `montant_total_vente`,
  `v`.`montant_payee` AS `montant_payee`,
  `v`.`montant_total_vente` - `v`.`montant_payee` AS `solde_du`,
  TO_DAYS(CURDATE()) - TO_DAYS(`v`.`date_vente`) AS `jours_retard`,
  CASE WHEN TO_DAYS(CURDATE()) - TO_DAYS(`v`.`date_vente`) <= 30 THEN '0-30 jours' WHEN TO_DAYS(CURDATE()) - TO_DAYS(`v`.`date_vente`) BETWEEN 31 AND 60 THEN '31-60 jours' WHEN TO_DAYS(CURDATE()) - TO_DAYS(`v`.`date_vente`) BETWEEN 61 AND 90 THEN '61-90 jours' ELSE '+90 jours' END AS `tranche_age`
FROM (`tventeproduitfini` `v`
  JOIN `tclient` `c`
    ON (`v`.`client_id` = `c`.`id`))
WHERE `v`.`montant_total_vente` - `v`.`montant_payee` > 0
UNION ALL
SELECT
  `f`.`id` AS `id_agent`,
  CONCAT(`f`.`nom`, ' ', `f`.`postnom`, ' ', `f`.`prenom`) AS `Agent_achat`,
  `ach`.`date_entree` AS `date_entree`,
  `ach`.`quantite` * `ach`.`prix_unitaire_entree` AS `montant_total`,
  `ach`.`montant_payer` AS `montant_payer`,
  `ach`.`quantite` * `ach`.`prix_unitaire_entree` - `ach`.`montant_payer` AS `solde_du`,
  TO_DAYS(CURDATE()) - TO_DAYS(`ach`.`date_entree`) AS `jours_retard`,
  CASE WHEN TO_DAYS(CURDATE()) - TO_DAYS(`ach`.`date_entree`) <= 30 THEN '0-30 jours' WHEN TO_DAYS(CURDATE()) - TO_DAYS(`ach`.`date_entree`) BETWEEN 31 AND 60 THEN '31-60 jours' WHEN TO_DAYS(CURDATE()) - TO_DAYS(`ach`.`date_entree`) BETWEEN 61 AND 90 THEN '61-90 jours' ELSE '+90 jours' END AS `tranche_age`
FROM (`tentreematiere` `ach`
  JOIN `tagent_achat` `f`
    ON (`ach`.`id` = `f`.`id`))
WHERE `ach`.`quantite` * `ach`.`prix_unitaire_entree` - `ach`.`montant_payer` > 0
ORDER BY `tranche_age`;

--
-- Create table `tconges`
--
CREATE TABLE tconges (
  id int(11) NOT NULL AUTO_INCREMENT,
  libelle varchar(100) DEFAULT NULL,
  jours_max int(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `tprendre_conges`
--
CREATE TABLE tprendre_conges (
  id int(11) NOT NULL AUTO_INCREMENT,
  id_agent int(11) DEFAULT NULL,
  idconge int(11) DEFAULT NULL,
  date_debut date DEFAULT NULL,
  date_fin date DEFAULT NULL,
  statut enum ('en_attente', 'approuve', 'rejete') DEFAULT 'en_attente',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tprendre_conges
ADD CONSTRAINT tprendre_conges_ibfk_1 FOREIGN KEY (id_agent)
REFERENCES tpersonnel (id);

--
-- Create foreign key
--
ALTER TABLE tprendre_conges
ADD CONSTRAINT tprendre_conges_ibfk_2 FOREIGN KEY (idconge)
REFERENCES tconges (id);

--
-- Create table `tretenues_salaire`
--
CREATE TABLE tretenues_salaire (
  id int(11) NOT NULL AUTO_INCREMENT,
  libelle varchar(100) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `tagent_retenues`
--
CREATE TABLE tagent_retenues (
  id int(11) NOT NULL AUTO_INCREMENT,
  id_agent int(11) DEFAULT NULL,
  id_retenue int(11) DEFAULT NULL,
  montant decimal(10, 2) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tagent_retenues
ADD CONSTRAINT tagent_retenues_ibfk_1 FOREIGN KEY (id_agent)
REFERENCES tpersonnel (id);

--
-- Create foreign key
--
ALTER TABLE tagent_retenues
ADD CONSTRAINT tagent_retenues_ibfk_2 FOREIGN KEY (id_retenue)
REFERENCES tretenues_salaire (id);

--
-- Create table `tavantages_salaire`
--
CREATE TABLE tavantages_salaire (
  id int(11) NOT NULL AUTO_INCREMENT,
  libelle varchar(100) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `taffect_avantages`
--
CREATE TABLE taffect_avantages (
  id int(11) NOT NULL AUTO_INCREMENT,
  id_agent int(11) DEFAULT NULL,
  id_avantage int(11) DEFAULT NULL,
  montant decimal(10, 2) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE taffect_avantages
ADD CONSTRAINT taffect_avantages_ibfk_1 FOREIGN KEY (id_agent)
REFERENCES tpersonnel (id);

--
-- Create foreign key
--
ALTER TABLE taffect_avantages
ADD CONSTRAINT taffect_avantages_ibfk_2 FOREIGN KEY (id_avantage)
REFERENCES tavantages_salaire (id);

--
-- Create table `tproduitfini`
--
CREATE TABLE tproduitfini (
  id int(11) NOT NULL AUTO_INCREMENT,
  code varchar(50) NOT NULL,
  libelle varchar(100) NOT NULL,
  unite varchar(20) DEFAULT 'PIECE',
  prix_unitaire decimal(10, 2) NOT NULL,
  stock_actuel decimal(10, 2) DEFAULT 0.00,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `usp_tproduitfini_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tproduitfini_Update (IN p_id int,
IN p_code varchar(50),
IN p_libelle varchar(100),
IN p_unite varchar(20),
IN p_prix_unitaire decimal(10, 2),
IN p_stock_actuel decimal(10, 2))
BEGIN
  START TRANSACTION;

    UPDATE tproduitfini
    SET code = p_code,
        libelle = p_libelle,
        unite = p_unite,
        prix_unitaire = p_prix_unitaire,
        stock_actuel = p_stock_actuel
    WHERE id = p_id;

  /*
  -- Begin Return row code block

  SELECT code, libelle, unite, prix_unitaire, stock_actuel
  FROM   tproduitfini
  WHERE  id = p_id;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tproduitfini_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tproduitfini_Select (IN p_id int)
BEGIN
  START TRANSACTION;

    SELECT
      id,
      code,
      libelle,
      unite,
      prix_unitaire,
      stock_actuel
    FROM tproduitfini
    WHERE id = p_id;

  COMMIT;
END
$$

--
-- Create procedure `usp_tproduitfini_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tproduitfini_Insert (IN p_code varchar(50),
IN p_libelle varchar(100),
IN p_unite varchar(20),
IN p_prix_unitaire decimal(10, 2),
IN p_stock_actuel decimal(10, 2))
BEGIN
  START TRANSACTION;

    INSERT INTO tproduitfini (code, libelle, unite, prix_unitaire, stock_actuel)
      VALUES (p_code, p_libelle, p_unite, p_prix_unitaire, p_stock_actuel);

  /*
  -- Begin Return row code block

  SELECT code, libelle, unite, prix_unitaire, stock_actuel
  FROM   tproduitfini
  WHERE  id = LAST_INSERT_ID();

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tproduitfini_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tproduitfini_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tproduitfini
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tentrees_pf`
--
CREATE TABLE tentrees_pf (
  id int(11) NOT NULL AUTO_INCREMENT,
  id_produit_fini int(11) NOT NULL,
  quantite_entree decimal(10, 2) NOT NULL,
  unite_mesure enum ('PIECE', 'KG', 'Litre') DEFAULT 'PIECE',
  date_entree timestamp NULL DEFAULT CURRENT_TIMESTAMP(),
  cout_production_unitaire decimal(10, 4) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tentrees_pf
ADD CONSTRAINT tentrees_pf_ibfk_1 FOREIGN KEY (id_produit_fini)
REFERENCES tproduitfini (id);

DELIMITER $$

--
-- Create procedure `usp_tentrees_pf_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tentrees_pf_Update (IN p_id int,
IN p_id_produit_fini int,
IN p_quantite_entree decimal(10, 2),
IN p_unite_mesure enum ('''PIECE''', '''KG''', '''Litre'''),
IN p_date_entree timestamp,
IN p_cout_production_unitaire decimal(10, 4))
BEGIN
  START TRANSACTION;

    UPDATE tentrees_pf
    SET id_produit_fini = p_id_produit_fini,
        quantite_entree = p_quantite_entree,
        unite_mesure = p_unite_mesure,
        date_entree = p_date_entree,
        cout_production_unitaire = p_cout_production_unitaire
    WHERE id = p_id;

  /*
  -- Begin Return row code block

  SELECT id_produit_fini, quantite_entree, unite_mesure, date_entree, cout_production_unitaire
  FROM   tentrees_pf
  WHERE  id = p_id;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tentrees_pf_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tentrees_pf_Select (IN p_id int)
BEGIN
  START TRANSACTION;

    SELECT
      id,
      id_produit_fini,
      quantite_entree,
      unite_mesure,
      date_entree,
      cout_production_unitaire
    FROM tentrees_pf
    WHERE id = p_id;

  COMMIT;
END
$$

--
-- Create procedure `usp_tentrees_pf_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tentrees_pf_Insert (IN p_id_produit_fini int,
IN p_quantite_entree decimal(10, 2),
IN p_unite_mesure enum ('''PIECE''', '''KG''', '''Litre'''),
IN p_date_entree timestamp,
IN p_cout_production_unitaire decimal(10, 4))
BEGIN
  START TRANSACTION;

    INSERT INTO tentrees_pf (id_produit_fini, quantite_entree, unite_mesure, date_entree, cout_production_unitaire)
      VALUES (p_id_produit_fini, p_quantite_entree, p_unite_mesure, p_date_entree, p_cout_production_unitaire);

  /*
  -- Begin Return row code block

  SELECT id_produit_fini, quantite_entree, unite_mesure, date_entree, cout_production_unitaire
  FROM   tentrees_pf
  WHERE  id = LAST_INSERT_ID();

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tentrees_pf_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tentrees_pf_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tentrees_pf
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tdetails_vente`
--
CREATE TABLE tdetails_vente (
  id int(11) NOT NULL AUTO_INCREMENT,
  id_vente int(11) NOT NULL,
  id_produit_fini int(11) NOT NULL,
  quantite_vendue decimal(10, 2) NOT NULL,
  prix_vente_unitaire_reel decimal(10, 2) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tdetails_vente
ADD CONSTRAINT tdetails_vente_ibfk_1 FOREIGN KEY (id_vente)
REFERENCES tventeproduitfini (id);

--
-- Create foreign key
--
ALTER TABLE tdetails_vente
ADD CONSTRAINT tdetails_vente_ibfk_2 FOREIGN KEY (id_produit_fini)
REFERENCES tproduitfini (id);

DELIMITER $$

--
-- Create procedure `usp_tdetails_vente_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tdetails_vente_Update (IN p_id int,
IN p_id_vente int,
IN p_id_produit_fini int,
IN p_quantite_vendue decimal(10, 2),
IN p_prix_vente_unitaire_reel decimal(10, 2))
BEGIN
  START TRANSACTION;

    UPDATE tdetails_vente
    SET id_vente = p_id_vente,
        id_produit_fini = p_id_produit_fini,
        quantite_vendue = p_quantite_vendue,
        prix_vente_unitaire_reel = p_prix_vente_unitaire_reel
    WHERE id = p_id;

  /*
  -- Begin Return row code block

  SELECT id_vente, id_produit_fini, quantite_vendue, prix_vente_unitaire_reel
  FROM   tdetails_vente
  WHERE  id = p_id;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tdetails_vente_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tdetails_vente_Select (IN p_id int)
BEGIN
  START TRANSACTION;

    SELECT
      id,
      id_vente,
      id_produit_fini,
      quantite_vendue,
      prix_vente_unitaire_reel
    FROM tdetails_vente
    WHERE id = p_id;

  COMMIT;
END
$$

--
-- Create procedure `usp_tdetails_vente_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tdetails_vente_Insert (IN p_id_vente int,
IN p_id_produit_fini int,
IN p_quantite_vendue decimal(10, 2),
IN p_prix_vente_unitaire_reel decimal(10, 2))
BEGIN
  START TRANSACTION;

    INSERT INTO tdetails_vente (id_vente, id_produit_fini, quantite_vendue, prix_vente_unitaire_reel)
      VALUES (p_id_vente, p_id_produit_fini, p_quantite_vendue, p_prix_vente_unitaire_reel);

  /*
  -- Begin Return row code block

  SELECT id_vente, id_produit_fini, quantite_vendue, prix_vente_unitaire_reel
  FROM   tdetails_vente
  WHERE  id = LAST_INSERT_ID();

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tdetails_vente_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tdetails_vente_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tdetails_vente
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tdetails_commandeclient`
--
CREATE TABLE tdetails_commandeclient (
  id_detail_commande int(11) NOT NULL AUTO_INCREMENT,
  id_commande int(11) NOT NULL,
  id_produit_fini int(11) NOT NULL,
  quantite_commandee decimal(10, 2) NOT NULL,
  prix_vente_unitaire decimal(10, 2) NOT NULL,
  PRIMARY KEY (id_detail_commande)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tdetails_commandeclient
ADD CONSTRAINT tdetails_commandeclient_ibfk_1 FOREIGN KEY (id_commande)
REFERENCES tcommandeclient (id);

--
-- Create foreign key
--
ALTER TABLE tdetails_commandeclient
ADD CONSTRAINT tdetails_commandeclient_ibfk_2 FOREIGN KEY (id_produit_fini)
REFERENCES tproduitfini (id);

DELIMITER $$

--
-- Create procedure `usp_tdetails_commandeclient_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tdetails_commandeclient_Update (IN p_id_detail_commande int,
IN p_id_commande int,
IN p_id_produit_fini int,
IN p_quantite_commandee decimal(10, 2),
IN p_prix_vente_unitaire decimal(10, 2))
BEGIN
  START TRANSACTION;

    UPDATE tdetails_commandeclient
    SET id_commande = p_id_commande,
        id_produit_fini = p_id_produit_fini,
        quantite_commandee = p_quantite_commandee,
        prix_vente_unitaire = p_prix_vente_unitaire
    WHERE id_detail_commande = p_id_detail_commande;

  /*
  -- Begin Return row code block

  SELECT id_commande, id_produit_fini, quantite_commandee, prix_vente_unitaire
  FROM   tdetails_commandeclient
  WHERE  id_detail_commande = p_id_detail_commande;

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tdetails_commandeclient_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tdetails_commandeclient_Select (IN p_id_detail_commande int)
BEGIN
  START TRANSACTION;

    SELECT
      id_detail_commande,
      id_commande,
      id_produit_fini,
      quantite_commandee,
      prix_vente_unitaire
    FROM tdetails_commandeclient
    WHERE id_detail_commande = p_id_detail_commande;

  COMMIT;
END
$$

--
-- Create procedure `usp_tdetails_commandeclient_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tdetails_commandeclient_Insert (IN p_id_commande int,
IN p_id_produit_fini int,
IN p_quantite_commandee decimal(10, 2),
IN p_prix_vente_unitaire decimal(10, 2))
BEGIN
  START TRANSACTION;

    INSERT INTO tdetails_commandeclient (id_commande, id_produit_fini, quantite_commandee, prix_vente_unitaire)
      VALUES (p_id_commande, p_id_produit_fini, p_quantite_commandee, p_prix_vente_unitaire);

  /*
  -- Begin Return row code block

  SELECT id_commande, id_produit_fini, quantite_commandee, prix_vente_unitaire
  FROM   tdetails_commandeclient
  WHERE  id_detail_commande = LAST_INSERT_ID();

  -- End Return row code block

  */
  COMMIT;
END
$$

--
-- Create procedure `usp_tdetails_commandeclient_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tdetails_commandeclient_Delete (p_id_detail_commande int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tdetails_commandeclient
      WHERE id_detail_commande = p_id_detail_commande;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tjournal`
--
CREATE TABLE tjournal (
  id int(11) NOT NULL AUTO_INCREMENT,
  codejr varchar(5) NOT NULL,
  nom_journal varchar(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `codejr` on table `tjournal`
--
ALTER TABLE tjournal
ADD UNIQUE INDEX codejr (codejr);

DELIMITER $$

--
-- Create procedure `usp_tjournal_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tjournal_Update (IN p_id int,
IN p_codejr varchar(5),
IN p_nom_journal varchar(50))
BEGIN
  START TRANSACTION;

    UPDATE tjournal
    SET codejr = p_codejr,
        nom_journal = p_nom_journal
    WHERE id = p_id;


    -- Begin Return row code block

    SELECT
      codejr,
      nom_journal
    FROM tjournal
    WHERE id = p_id;

  -- End Return row code block


  COMMIT;
END
$$

--
-- Create procedure `usp_tjournal_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tjournal_Select (IN p_id int)
BEGIN
  START TRANSACTION;

    SELECT
      id,
      codejr,
      nom_journal
    FROM tjournal
    ;

  COMMIT;
END
$$

--
-- Create procedure `usp_tjournal_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tjournal_Insert (IN p_codejr varchar(5),
IN p_nom_journal varchar(50))
BEGIN
  START TRANSACTION;

    INSERT INTO tjournal (codejr, nom_journal)
      VALUES (p_codejr, p_nom_journal);


    -- Begin Return row code block

    SELECT
      codejr,
      nom_journal
    FROM tjournal
    WHERE id = LAST_INSERT_ID();

  -- End Return row code block


  COMMIT;
END
$$

--
-- Create procedure `usp_tjournal_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tjournal_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tjournal
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create table `tecritures_comptables`
--
CREATE TABLE tecritures_comptables (
  id int(11) NOT NULL AUTO_INCREMENT,
  journal_id int(11) NOT NULL,
  numdocument varchar(10) NOT NULL,
  sous_compte_id int(11) NOT NULL,
  sens enum ('C', 'CP') NOT NULL,
  libelle text DEFAULT NULL,
  sous_compte_cp int(11) DEFAULT NULL,
  date_ecriture datetime NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  montant decimal(15, 2) NOT NULL,
  um enum ('USD', 'FC') NOT NULL,
  taux_convertion_usd_fc decimal(10, 2) NOT NULL,
  id_user varchar(255) DEFAULT NULL,
  column1 int(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE tecritures_comptables
ADD CONSTRAINT tecritures_comptables_ibfk_1 FOREIGN KEY (journal_id)
REFERENCES tjournal (id);

--
-- Create foreign key
--
ALTER TABLE tecritures_comptables
ADD CONSTRAINT tecritures_comptables_ibfk_2 FOREIGN KEY (sous_compte_id)
REFERENCES tsous_comptes (id);

--
-- Create foreign key
--
ALTER TABLE tecritures_comptables
ADD CONSTRAINT tecritures_comptables_ibfk_3 FOREIGN KEY (sous_compte_cp)
REFERENCES tsous_comptes (id);

DELIMITER $$

--
-- Create procedure `usp_tecritures_comptables_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tecritures_comptables_Update (IN p_id int,
IN p_journal_id int,
IN p_numdocument varchar(10),
IN p_sous_compte_id int,
IN p_sens enum ('''C''', '''CP'''),
IN p_libelle text,
IN p_sous_compte_cp int,
IN p_date_ecriture datetime,
IN p_montant decimal(15, 2),
IN p_um enum ('''USD''', '''FC'''),
IN p_taux_convertion_usd_fc decimal(10, 2))
BEGIN
  START TRANSACTION;

    UPDATE tecritures_comptables
    SET journal_id = p_journal_id,
        numdocument = p_numdocument,
        sous_compte_id = p_sous_compte_id,
        sens = p_sens,
        libelle = p_libelle,
        sous_compte_cp = p_sous_compte_cp,
        date_ecriture = p_date_ecriture,
        montant = p_montant,
        um = p_um,
        taux_convertion_usd_fc = p_taux_convertion_usd_fc
    WHERE id = p_id;


    -- Begin Return row code block

    SELECT
      journal_id,
      numdocument,
      sous_compte_id,
      sens,
      libelle,
      sous_compte_cp,
      date_ecriture,
      montant,
      um,
      taux_convertion_usd_fc
    FROM tecritures_comptables
    WHERE id = p_id;

  -- End Return row code block


  COMMIT;
END
$$

--
-- Create procedure `usp_tecritures_comptables_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tecritures_comptables_Select (IN p_id int)
BEGIN
  START TRANSACTION;

    SELECT
      id,
      journal_id,
      numdocument,
      sous_compte_id,
      sens,
      libelle,
      sous_compte_cp,
      date_ecriture,
      montant,
      um,
      taux_convertion_usd_fc
    FROM tecritures_comptables
    ;

  COMMIT;
END
$$

--
-- Create procedure `usp_tecritures_comptables_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tecritures_comptables_Insert (IN p_journal_id int,
IN p_numdocument varchar(10),
IN p_sous_compte_id int,
IN p_sens enum ('''C''', '''CP'''),
IN p_libelle text,
IN p_sous_compte_cp int,
IN p_date_ecriture datetime,
IN p_montant decimal(15, 2),
IN p_um enum ('''USD''', '''FC'''),
IN p_taux_convertion_usd_fc decimal(10, 2))
BEGIN
  START TRANSACTION;

    INSERT INTO tecritures_comptables (journal_id, numdocument, sous_compte_id, sens, libelle, sous_compte_cp,
    date_ecriture, montant, um, taux_convertion_usd_fc)
      VALUES (p_journal_id, p_numdocument, p_sous_compte_id, p_sens, p_libelle, p_sous_compte_cp, p_date_ecriture,
      p_montant, p_um, p_taux_convertion_usd_fc);


    -- Begin Return row code block

    SELECT
      journal_id,
      numdocument,
      sous_compte_id,
      sens,
      libelle,
      sous_compte_cp,
      date_ecriture,
      montant,
      um,
      taux_convertion_usd_fc
    FROM tecritures_comptables
    WHERE id = LAST_INSERT_ID();

  -- End Return row code block


  COMMIT;
END
$$

--
-- Create procedure `usp_tecritures_comptables_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tecritures_comptables_Delete (p_id int)
BEGIN
  START TRANSACTION;

    DELETE
      FROM tecritures_comptables
      WHERE id = p_id;

      COMMIT;
      END
      $$

DELIMITER ;

--
-- Create view `v_synthese_financiere`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_synthese_financiere
AS
SELECT
  `n`.`nature_compte` AS `nature_compte`,
  `c`.`numero` AS `compte`,
  `c`.`intitule` AS `compte_intitule`,
  `sc`.`numero` AS `sous_compte`,
  `sc`.`intitule` AS `sous_compte_intitule`,
  SUM(CASE WHEN `n`.`nature_compte` = 'ACTIF' AND
      `e`.`sens` = 'CP' THEN `e`.`montant` WHEN `n`.`nature_compte` = 'ACTIF' AND
      `e`.`sens` = 'C' THEN -`e`.`montant` WHEN `n`.`nature_compte` = 'PASSIF' AND
      `e`.`sens` = 'C' THEN `e`.`montant` WHEN `n`.`nature_compte` = 'PASSIF' AND
      `e`.`sens` = 'CP' THEN -`e`.`montant` WHEN `n`.`nature_compte` = 'CHARGES' AND
      `e`.`sens` = 'CP' THEN `e`.`montant` WHEN `n`.`nature_compte` = 'CHARGES' AND
      `e`.`sens` = 'C' THEN -`e`.`montant` WHEN `n`.`nature_compte` = 'PRODUITS' AND
      `e`.`sens` = 'C' THEN `e`.`montant` WHEN `n`.`nature_compte` = 'PRODUITS' AND
      `e`.`sens` = 'CP' THEN -`e`.`montant` ELSE 0 END) AS `solde`
FROM (((`tecritures_comptables` `e`
  JOIN `tsous_comptes` `sc`
    ON (`e`.`sous_compte_id` = `sc`.`id`))
  JOIN `tcomptes` `c`
    ON (`sc`.`compte_id` = `c`.`id`))
  JOIN `tnature_compte` `n`
    ON (`c`.`id_naturecompte` = `n`.`id_nature`))
GROUP BY `n`.`nature_compte`,
         `c`.`numero`,
         `c`.`intitule`,
         `sc`.`numero`,
         `sc`.`intitule`
ORDER BY FIELD(`n`.`nature_compte`, 'ACTIF', 'PASSIF', 'CHARGES', 'PRODUITS'), `c`.`numero`, `sc`.`numero`;

--
-- Create view `v_resultat_net`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_resultat_net
AS
SELECT
  SUM(CASE WHEN `n`.`nature_compte` = 'CHARGES' AND
      `e`.`sens` = 'CP' THEN `e`.`montant` WHEN `n`.`nature_compte` = 'CHARGES' AND
      `e`.`sens` = 'C' THEN -`e`.`montant` WHEN `n`.`nature_compte` = 'PRODUITS' AND
      `e`.`sens` = 'C' THEN `e`.`montant` WHEN `n`.`nature_compte` = 'PRODUITS' AND
      `e`.`sens` = 'CP' THEN -`e`.`montant` ELSE 0 END) AS `resultat_net`
FROM (((`tecritures_comptables` `e`
  JOIN `tsous_comptes` `sc`
    ON (`e`.`sous_compte_id` = `sc`.`id`))
  JOIN `tcomptes` `c`
    ON (`sc`.`compte_id` = `c`.`id`))
  JOIN `tnature_compte` `n`
    ON (`c`.`id_naturecompte` = `n`.`id_nature`))
WHERE `n`.`nature_compte` IN ('CHARGES', 'PRODUITS');

--
-- Create view `v_journal_operations`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_journal_operations
AS
SELECT
  `e`.`id` AS `id_ecriture`,
  `e`.`date_ecriture` AS `date_ecriture`,
  `e`.`libelle` AS `libelle`,
  `c`.`numero` AS `compte`,
  `c`.`intitule` AS `compte_intitule`,
  `sc`.`numero` AS `sous_compte`,
  `sc`.`intitule` AS `sous_compte_intitule`,
  CASE WHEN `e`.`sens` = 'CP' THEN `e`.`montant` ELSE 0 END AS `debit`,
  CASE WHEN `e`.`sens` = 'C' THEN `e`.`montant` ELSE 0 END AS `credit`,
  `e`.`um` AS `um`,
  `e`.`numdocument` AS `numdocument`,
  `e`.`id_user` AS `id_user`
FROM ((`tecritures_comptables` `e`
  JOIN `tsous_comptes` `sc`
    ON (`e`.`sous_compte_id` = `sc`.`id`))
  JOIN `tcomptes` `c`
    ON (`sc`.`compte_id` = `c`.`id`))
ORDER BY `e`.`date_ecriture`, `e`.`id`;

--
-- Create view `v_compte_resultat`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_compte_resultat
AS
SELECT
  `n`.`nature_compte` AS `nature_compte`,
  `c`.`numero` AS `compte`,
  `c`.`intitule` AS `compte_intitule`,
  `sc`.`numero` AS `sous_compte`,
  `sc`.`intitule` AS `sous_compte_intitule`,
  SUM(CASE WHEN `n`.`nature_compte` = 'CHARGES' AND
      `e`.`sens` = 'CP' THEN `e`.`montant` WHEN `n`.`nature_compte` = 'CHARGES' AND
      `e`.`sens` = 'C' THEN -`e`.`montant` WHEN `n`.`nature_compte` = 'PRODUITS' AND
      `e`.`sens` = 'C' THEN `e`.`montant` WHEN `n`.`nature_compte` = 'PRODUITS' AND
      `e`.`sens` = 'CP' THEN -`e`.`montant` ELSE 0 END) AS `solde`
FROM (((`tecritures_comptables` `e`
  JOIN `tsous_comptes` `sc`
    ON (`e`.`sous_compte_id` = `sc`.`id`))
  JOIN `tcomptes` `c`
    ON (`sc`.`compte_id` = `c`.`id`))
  JOIN `tnature_compte` `n`
    ON (`c`.`id_naturecompte` = `n`.`id_nature`))
WHERE `n`.`nature_compte` IN ('CHARGES', 'PRODUITS')
GROUP BY `n`.`nature_compte`,
         `c`.`numero`,
         `c`.`intitule`,
         `sc`.`numero`,
         `sc`.`intitule`
ORDER BY `n`.`nature_compte`, `c`.`numero`, `sc`.`numero`;

--
-- Create view `v_bilan`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_bilan
AS
SELECT
  `n`.`nature_compte` AS `nature_compte`,
  `c`.`numero` AS `compte`,
  `c`.`intitule` AS `compte_intitule`,
  `sc`.`numero` AS `sous_compte`,
  `sc`.`intitule` AS `sous_compte_intitule`,
  SUM(CASE WHEN `n`.`nature_compte` = 'ACTIF' AND
      `e`.`sens` = 'CP' THEN `e`.`montant` WHEN `n`.`nature_compte` = 'ACTIF' AND
      `e`.`sens` = 'C' THEN -`e`.`montant` WHEN `n`.`nature_compte` = 'PASSIF' AND
      `e`.`sens` = 'C' THEN `e`.`montant` WHEN `n`.`nature_compte` = 'PASSIF' AND
      `e`.`sens` = 'CP' THEN -`e`.`montant` ELSE 0 END) AS `solde`
FROM (((`tecritures_comptables` `e`
  JOIN `tsous_comptes` `sc`
    ON (`e`.`sous_compte_id` = `sc`.`id`))
  JOIN `tcomptes` `c`
    ON (`sc`.`compte_id` = `c`.`id`))
  JOIN `tnature_compte` `n`
    ON (`c`.`id_naturecompte` = `n`.`id_nature`))
GROUP BY `n`.`nature_compte`,
         `c`.`numero`,
         `c`.`intitule`,
         `sc`.`numero`,
         `sc`.`intitule`
ORDER BY `n`.`nature_compte`, `c`.`numero`, `sc`.`numero`;

--
-- Create view `v_balance_generale`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_balance_generale
AS
SELECT
  `c`.`numero` AS `compte`,
  `c`.`intitule` AS `compte_intitule`,
  SUM(CASE WHEN `e`.`sens` = 'CP' THEN `e`.`montant` ELSE 0 END) AS `total_debit`,
  SUM(CASE WHEN `e`.`sens` = 'C' THEN `e`.`montant` ELSE 0 END) AS `total_credit`,
  SUM(CASE WHEN `e`.`sens` = 'CP' THEN `e`.`montant` ELSE 0 END) - SUM(CASE WHEN `e`.`sens` = 'C' THEN `e`.`montant` ELSE 0 END) AS `solde`
FROM ((`tecritures_comptables` `e`
  JOIN `tsous_comptes` `sc`
    ON (`e`.`sous_compte_id` = `sc`.`id`))
  JOIN `tcomptes` `c`
    ON (`sc`.`compte_id` = `c`.`id`))
GROUP BY `c`.`numero`,
         `c`.`intitule`
ORDER BY `c`.`numero`;

--
-- Create view `v_balance_comptes`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW v_balance_comptes
AS
SELECT
  `c`.`numero` AS `compte`,
  `c`.`intitule` AS `compte_intitule`,
  `sc`.`numero` AS `sous_compte`,
  `sc`.`intitule` AS `sous_compte_intitule`,
  SUM(CASE WHEN `e`.`sens` = 'CP' THEN `e`.`montant` ELSE 0 END) AS `total_debit`,
  SUM(CASE WHEN `e`.`sens` = 'C' THEN `e`.`montant` ELSE 0 END) AS `total_credit`,
  SUM(CASE WHEN `e`.`sens` = 'CP' THEN `e`.`montant` ELSE 0 END) - SUM(CASE WHEN `e`.`sens` = 'C' THEN `e`.`montant` ELSE 0 END) AS `solde`
FROM ((`tecritures_comptables` `e`
  JOIN `tsous_comptes` `sc`
    ON (`e`.`sous_compte_id` = `sc`.`id`))
  JOIN `tcomptes` `c`
    ON (`sc`.`compte_id` = `c`.`id`))
GROUP BY `c`.`numero`,
         `c`.`intitule`,
         `sc`.`numero`,
         `sc`.`intitule`
ORDER BY `c`.`numero`, `sc`.`numero`;

--
-- Create table `troles`
--
CREATE TABLE troles (
  id int(11) NOT NULL AUTO_INCREMENT,
  nom_role varchar(50) NOT NULL,
  description text DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `nom_role` on table `troles`
--
ALTER TABLE troles
ADD UNIQUE INDEX nom_role (nom_role);

--
-- Create table `tutilisateurs`
--
CREATE TABLE tutilisateurs (
  id int(11) NOT NULL AUTO_INCREMENT,
  nom_utilisateur varchar(50) NOT NULL,
  mot_de_passe varchar(255) NOT NULL,
  email varchar(100) DEFAULT NULL,
  statut enum ('Actif', 'Inactif') DEFAULT 'Actif',
  role_id int(11) DEFAULT NULL,
  date_creation timestamp NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `nom_utilisateur` on table `tutilisateurs`
--
ALTER TABLE tutilisateurs
ADD UNIQUE INDEX nom_utilisateur (nom_utilisateur);

--
-- Create foreign key
--
ALTER TABLE tutilisateurs
ADD CONSTRAINT tutilisateurs_ibfk_1 FOREIGN KEY (role_id)
REFERENCES troles (id);

DELIMITER $$

--
-- Create procedure `pr_login_user`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE pr_login_user (IN _nom_utilisateur varchar(50),
IN _mot_de_passe varchar(255))
BEGIN
  DECLARE v_user_id int;
  DECLARE v_role_id int;
  DECLARE v_statut varchar(10);

  -- Vérifier si l'utilisateur existe
  SELECT
    id,
    role_id,
    statut INTO v_user_id, v_role_id, v_statut
  FROM tutilisateurs
  WHERE nom_utilisateur = _nom_utilisateur
  AND mot_de_passe = SHA2(_mot_de_passe, 256)
  LIMIT 1;

  -- Si utilisateur non trouvé
  IF v_user_id IS NULL THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = 'Nom d''utilisateur ou mot de passe incorrect';
  END IF;

  -- Si utilisateur inactif
  IF v_statut = 'Inactif' THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = 'Utilisateur inactif, contactez l''administrateur';
  END IF;

  -- Retourner les infos utilisateur avec le rôle
  SELECT
    u.id AS utilisateur_id,
    u.nom_utilisateur,
    u.email,
    u.statut,
    r.nom_role,
    r.description AS role_description
  FROM tutilisateurs u
    JOIN troles r
      ON u.role_id = r.id
  WHERE u.id = v_user_id;

END
$$

--
-- Create procedure `pr_create_user`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE pr_create_user (IN _nom_utilisateur varchar(50),
IN _mot_de_passe varchar(255),
IN _email varchar(100),
IN _role_id int)
BEGIN
  -- Vérifier si l’utilisateur existe déjà
  IF EXISTS (SELECT
        1
      FROM tutilisateurs
      WHERE nom_utilisateur = _nom_utilisateur) THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = 'Utilisateur déjà existant';
  ELSE
    INSERT INTO tutilisateurs (nom_utilisateur, mot_de_passe, email, role_id)
      VALUES (_nom_utilisateur, SHA2(_mot_de_passe, 256), _email, _role_id);
  END IF;
END
$$

DELIMITER ;

--
-- Create table `tjours_feries`
--
CREATE TABLE tjours_feries (
  id int(11) NOT NULL AUTO_INCREMENT,
  date_ferie date DEFAULT NULL,
  description varchar(100) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `t_profils`
--
CREATE TABLE t_profils (
  id_profil int(11) NOT NULL AUTO_INCREMENT,
  profil_code varchar(10) NOT NULL,
  profil_nom varchar(100) NOT NULL,
  PRIMARY KEY (id_profil)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `profil_code` on table `t_profils`
--
ALTER TABLE t_profils
ADD UNIQUE INDEX profil_code (profil_code);

--
-- Create table `t_familles_comptables`
--
CREATE TABLE t_familles_comptables (
  id_famille int(11) NOT NULL AUTO_INCREMENT,
  famille_code varchar(10) NOT NULL,
  famille_nom varchar(100) NOT NULL,
  id_classe int(11) DEFAULT NULL,
  PRIMARY KEY (id_famille)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_uca1400_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `famille_code` on table `t_familles_comptables`
--
ALTER TABLE t_familles_comptables
ADD UNIQUE INDEX famille_code (famille_code);

DELIMITER $$

--
-- Create procedure `usp_tprofils_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tprofils_Update (IN _id_profil int,
IN _profil_code varchar(10),
IN _profil_nom varchar(100))
BEGIN
  UPDATE t_profils
  SET profil_code = _profil_code,
      profil_nom = _profil_nom
  WHERE id_profil = _id_profil;
END
$$

--
-- Create procedure `usp_tprofils_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tprofils_Select ()
BEGIN
  SELECT
    *
  FROM t_profils;
END
$$

--
-- Create procedure `usp_tprofils_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tprofils_Insert (IN _profil_code varchar(10),
IN _profil_nom varchar(100))
BEGIN
  INSERT INTO t_profils (profil_code,
  profil_nom)
    VALUES
    (_profil_code,
    _profil_nom);
END
$$

--
-- Create procedure `usp_tprofils_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tprofils_Delete (IN _id_profil int)
BEGIN
  DELETE
    FROM t_profils
    WHERE id_profil = _id_profil;
    END
    $$

--
-- Create procedure `usp_tfamilles_comptables_Update`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tfamilles_comptables_Update (IN _id_famille int,
IN _famille_code varchar(10),
IN _famille_nom varchar(100),
IN _id_classe int)
BEGIN
  UPDATE t_familles_comptables
  SET famille_code = _famille_code,
      famille_nom = _famille_nom,
      id_classe = _id_classe
  WHERE id_famille = _id_famille;
END
$$

--
-- Create procedure `usp_tfamilles_comptables_Select`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tfamilles_comptables_Select ()
BEGIN
  SELECT
    *
  FROM t_familles_comptables;
END
$$

--
-- Create procedure `usp_tfamilles_comptables_Insert`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tfamilles_comptables_Insert (IN _famille_code varchar(10),
IN _famille_nom varchar(100),
IN _id_classe int)
BEGIN
  INSERT INTO t_familles_comptables (famille_code,
  famille_nom,
  id_classe)
    VALUES
    (_famille_code,
    _famille_nom,
    _id_classe);
END
$$

--
-- Create procedure `usp_tfamilles_comptables_Delete`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE usp_tfamilles_comptables_Delete (IN _id_famille int)
BEGIN
  DELETE
    FROM t_familles_comptables
    WHERE id_famille = _id_famille;
    END
    $$

DELIMITER ;

--
-- Dumping data for table tnature_compte
--
INSERT INTO tnature_compte VALUES
(1, 'ACTIF'),
(2, 'PASSIF'),
(3, 'CHARGES'),
(4, 'PRODUITS');

--
-- Dumping data for table tmasse_bilantaire
--
INSERT INTO tmasse_bilantaire VALUES
(1, 'ACTIFS IMMOBILISES'),
(2, 'ACTIFS CIRCULANTS'),
(3, 'ACTIFS DE TRESORERIE'),
(4, 'CAPITAUX PROPRES'),
(5, 'DETTES FINANCIERES'),
(6, 'PASSIFS CIRCULANT');

--
-- Dumping data for table tcomptes
--
INSERT INTO tcomptes VALUES
(1, '10', 'CAPITAL', 4, 2),
(2, '11', 'RESERVE', 4, 2),
(3, '12', 'REPORT', 4, 2),
(4, '13', 'RESULTAT', 4, 2),
(5, '16', 'EMPRUNT', 5, 2),
(6, '23', 'AMENAGEMENT', 1, 1),
(7, '24', 'MATERIEL', 1, 1),
(8, '27', 'PRETS', 1, 1),
(9, '28', 'AMORTISSEMENTS', 1, 1),
(10, '32', 'MATIERES PRIEMIERES ET FOURNITURES LIEES', 2, 1),
(11, '36', 'PRODUITS FINIS', 2, 1),
(12, '40', 'FOURNISSEURS', 6, 2),
(13, '41', 'CLIENTS', 2, 1),
(14, '42', 'PERSONNEL', 2, 1),
(15, '4711', 'DEBITEURS DIVERS', 2, 1),
(16, '4712', 'CREDITEURS DIVERS', 6, 2);

--
-- Dumping data for table troles
--
INSERT INTO troles VALUES
(1, 'Administrateur', 'Accès complet au système'),
(2, 'Comptable', 'Accès aux écritures et rapports financiers'),
(3, 'Caissier', 'Accès aux paiements et encaissements'),
(4, 'RH', 'Accès à la gestion du personnel');

-- Table db_pvc_renovee.tconges does not contain any data (it is empty)

-- Table db_pvc_renovee.tmateriels does not contain any data (it is empty)

-- Table db_pvc_renovee.tclient does not contain any data (it is empty)

--
-- Dumping data for table tmatierepremiere
--
INSERT INTO tmatierepremiere VALUES
(1, 'REF001', 'Matière A', 'KG', 100.00, 50.00, 10.00),
(2, 'PVC1', 'Pvc 32pouce', 'PIECE', 0.00, 0.00, 2.00);

-- Table db_pvc_renovee.tagent_achat does not contain any data (it is empty)

-- Table db_pvc_renovee.tsous_comptes does not contain any data (it is empty)

-- Table db_pvc_renovee.tjournal does not contain any data (it is empty)

-- Table db_pvc_renovee.tventeproduitfini does not contain any data (it is empty)

-- Table db_pvc_renovee.tproduitfini does not contain any data (it is empty)

-- Table db_pvc_renovee.tcommandeclient does not contain any data (it is empty)

-- Table db_pvc_renovee.tretenues_salaire does not contain any data (it is empty)

-- Table db_pvc_renovee.tavantages_salaire does not contain any data (it is empty)

-- Table db_pvc_renovee.tpostes does not contain any data (it is empty)

-- Table db_pvc_renovee.tpersonnel does not contain any data (it is empty)

--
-- Dumping data for table tutilisateurs
--
INSERT INTO tutilisateurs VALUES
(1, 'Lus', '9c718bcfcfea052b6c58ff070625a6bff9c9b915995b620af1766efa2ecee900', 'louangelusenge06@gmail.com', 'Actif', 1, '2025-09-04 11:20:52');

-- Table db_pvc_renovee.tsortiematiere does not contain any data (it is empty)

-- Table db_pvc_renovee.tpresences does not contain any data (it is empty)

-- Table db_pvc_renovee.tprendre_conges does not contain any data (it is empty)

-- Table db_pvc_renovee.tplan_amortissements does not contain any data (it is empty)

-- Table db_pvc_renovee.tpaiements_clients does not contain any data (it is empty)

-- Table db_pvc_renovee.tjours_feries does not contain any data (it is empty)

-- Table db_pvc_renovee.tentrees_pf does not contain any data (it is empty)

-- Table db_pvc_renovee.tentreematiere does not contain any data (it is empty)

-- Table db_pvc_renovee.tecritures_comptables does not contain any data (it is empty)

-- Table db_pvc_renovee.tdetails_vente does not contain any data (it is empty)

-- Table db_pvc_renovee.tdetails_commandeclient does not contain any data (it is empty)

-- Table db_pvc_renovee.tagent_retenues does not contain any data (it is empty)

-- Table db_pvc_renovee.taffect_avantages does not contain any data (it is empty)

-- Table db_pvc_renovee.taffectations_personnel does not contain any data (it is empty)

--
-- Set default database
--
USE db_pvc_renovee;

--
-- Drop trigger `trigger1`
--
DROP TRIGGER IF EXISTS trigger1;

--
-- Set default database
--
USE db_pvc_renovee;

DELIMITER $$

--
-- Create trigger `trigger1`
--
CREATE
DEFINER = 'root'@'localhost'
TRIGGER trigger1
AFTER INSERT
ON tmateriels
FOR EACH ROW
BEGIN

  SET @_id_materiel = new.id_materiel;
  SET @_date_amort = new.date_acquisition;
  SET @_valeur_base = new.valeur_acquisition;
  SET @_taux = new.taux_amortissement;
  SET @_periodicite = new.periodicite;
  SET @_duree = new.duree_utilisation;
  SET @_valeur_nette = new.valeur_residuelle;
  SET @_mode_amort = new.mode_amortissement;
  SET @_Coefficient_degressif = new.Coefficient_degressif;
  CALL pr_insert_plan_amort(@_id_materiel, @_date_amort, @_valeur_base, @_taux, @_periodicite, @_duree, @_valeur_nette, @_mode_amort, @_Coefficient_degressif);

END
$$

DELIMITER ;

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;
